### ISSUE TITLE
[Vim] Cursor in Vim editor is not working properly

### ISSUE THREAD

**Issue by Publicker** [taniarascia/takenote#100]
### Issue and Steps to Reproduce

1.  Settings
2. Enable `Vim Mode`
3. Create a new note
4. Put insert mode into the editor (press `i`)
5. Write some text
6. With arrow keys of your keyboards go left and right

### Attachment
![vim-cursor-bug](https://user-images.githubusercontent.com/52673485/67025819-0bec8780-f0dd-11e9-9067-a407354219c0.gif)

#### Expected
The cursor move with your arrow keys movements
#### Actual
The cursor is fixed at the last position of it.

**Comment by ralmeidaa** [comment]
Hi I would like to take a look into it.. I managed to replicate the issue locally

**Comment by taniarascia** [comment]
Fixed.

**Comment by taniarascia** [comment]
I thought I fixed it...but maybe not.

**Comment by taniarascia** [comment]
Using `editor.refresh()` fixes it, but I'm not sure the best place to put it. I'm sure we shouldn't be calling it over and over again, just once when Vim mode gets set.

**Comment by taniarascia** [comment]
I made this SO post for now to document my issue: https://stackoverflow.com/questions/58444380/use-useeffect-to-respond-to-redux-state-change

**Comment by taniarascia** [comment]
Refresh doesn't seem to work either. :(

**Comment by taniarascia** [comment]
https://github.com/scniro/react-codemirror2/issues/37 Here's the issue...

**Comment by ralmeidaa** [comment]
@taniarascia yep I was playing with the ```editor.refresh() ``` method and the autorefresh property.

**Comment by taniarascia** [comment]
Looks like there’s no solution, so I’ll simply remove Vim mode for now.
