### ISSUE TITLE
Improvement on the note search

### ISSUE THREAD

**Issue by opw0011** [taniarascia/takenote#109]
Currently the note search filter out notes, which match on the title or the content.

However, it seems unnatural to me at the first glance:

I thought the search box was only for searching note title, but eventually some other notes came out because the content contains the keyword. Let's imagine when there are some notes contain thousands of words, then they have a high chance to be filtered out every time because of the content match! 

So, would it be better if we separate into several types of search:
1) Title search (just keep it in current search box)
2) Content search on current active note (perhaps when the cursor is on the note, trigger by ctrl+f)
3) Full text search across all the notes (maybe ctrl+shift+f)

These are some my opinions, open to discussion. 😃

**Comment by taniarascia** [comment]
I totally understand your point, but I know how unorganized I am, and I don’t end up knowing what I title my notes. I just know I had some phrase somewhere in some note. So for me, filtering the whole store is more useful. I can already search the active note with the default browser search.

**Comment by taniarascia** [comment]
Highlighting the search term might be a good idea though.
