### ISSUE TITLE
Always display "Favorite" notes pinned to top of NoteList (with icon)

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#110]

**Comment by Publicker** [comment]
Hi!

I think that I can do it 😁

**Comment by JakeHL** [comment]
> Hi!
> 
> I think that I can do it 😁

Ah! I've just put in a PR for this - sorry for stepping on your toes! 😓

**Comment by Publicker** [comment]
Oh!
No problem!

**Comment by taniarascia** [comment]
Closed in #121
