### ISSUE TITLE
Toggle sync settings on and off

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#112]
Right now, the app syncs to localStorage every 30 seconds.

In KeyboardShortcuts.tsx, an interval is set.

  useInterval(() => {
    _syncState(notes, categories)
  }, 30000)
This should not be in Keyboard Shortcuts, but more likely App.tsx or SettingsModal.tsx. The settings modal should have an option to toggle sync on and off, and set sync interval.

A sensible default should be set - sync on and set to 30 seconds, and the user should be able to turn it off. Bonus points if the sync doesn't go through if the last updated note is within 5 seconds or something - to prevent sync while typing.

**Comment by anooppoommen** [comment]
Hey is this up for grabs

**Comment by taniarascia** [comment]
I moved it to a better spot for now, but I don't think I'll turn off sync.
