### ISSUE TITLE
Large notes do not display all content until clicked

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#12]
If you make a very long note, it only displays the first thousand or so characters until you click on the editor, then the rest appears.

**Comment by AM-Myrick** [comment]
Hi @taniarascia, I was just trying to replicate this bug and I realized I was pasting in a new line before the actual note. Is it possible you made the same mistake? I'm not seeing this bug when I get rid of the new line I pasted in. The notes in the picture below all have over 4,000 characters.

Please let me know if I'm misunderstanding this issue, I haven't contributed to open source before and I'm looking for ways to help.

<img width="300" alt="Screen Shot 2019-10-12 at 5 13 44 PM" src="https://user-images.githubusercontent.com/32982005/66707752-ce21e480-ed13-11e9-8b07-d643f5263248.png">

**Comment by taniarascia** [comment]
Hi! That’s a good point, and a new bug! This bug is that the note itself seems to only display partial content if very long if you try to scroll without clicking on it. The other bug is that the title won’t display if you start the note with a new line, thanks for informing me of that!

**Comment by taniarascia** [comment]
`editor.refresh()` fixes this, but I need to figure out how to do it after a new note gets loaded.
