### ISSUE TITLE
Display an icon with sync state

### ISSUE THREAD

**Issue by Jfelix61** [taniarascia/takenote#122]
## Motivation
As of right now, the user does not know when the notes are synced or not. Having an indicator will allow the user to know if his notes are sync and can exit the tab safely. 

## Description
Display an icon when notes are not synced and vice versa.

**Comment by taniarascia** [comment]
Technically, the sync icon will become a loading icon already during syncing, but it happens to fast to see since it's not hooked up with an API yet. Putting the date of "last synced" somewhere would be helpful.
