### ISSUE TITLE
Note title is not working with UTF-8 Characters

### ISSUE THREAD

**Issue by rezaamya** [taniarascia/takenote#128]
If you write in UTF-8, it won't add to note title.
I wrote "Hi Tania" in first line in Persian, but it not working.
![image](https://user-images.githubusercontent.com/8912282/67131796-ed88a800-f212-11e9-8f28-fea885e66e41.png)

As you can see, I have tested one with English characters and it is working correctly. 
(because probably you don't have Persian keyboard and you want to test, I will add it in new line for your test!
سلام تانیا
)

**Comment by taniarascia** [comment]
Fixed in #118

**Comment by taniarascia** [comment]
Fix broke regular English, so will need to look into it further.
