### ISSUE TITLE
Style app and make responsive

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#13]
- Properly style app
- Make mobile/tablet responsive

**Comment by taniarascia** [comment]
- Choose a primary color
- Set all colors and font styles in variables 
- Base padding and margins on a base variable
- Allow collapsing of sidebar (both?)
- Make classes consistent and reusable

**Comment by liloo2040** [comment]
Hello! I would like to help you on this!

**Comment by scanf** [comment]
Hei, I was about to open an issue on this. It's currently unusable on iOS. Let me know if you need someone to try out. Below are some screenshots I took while trying to make notes on my phone.

![IMG_2052](https://user-images.githubusercontent.com/925044/67137304-26d11000-f233-11e9-9af3-ea8be1e98552.png)
![IMG_2053](https://user-images.githubusercontent.com/925044/67137305-26d11000-f233-11e9-8835-1928e893561d.png)

**Comment by taniarascia** [comment]
Yes, it has not been made mobile friendly yet.

**Comment by Publicker** [comment]
Hi!

Do you have any plan to integrate the project with any CSS framework?
I was specifically thinking about [Tailwind CSS](https://tailwindcss.com/). What do you think?

**Comment by taniarascia** [comment]
Looks like a pretty nice framework! No plans to integrate for now. I like that every line of the CSS is actually being used. :D

**Comment by Publicker** [comment]
I like it! 🙌

**Comment by dagda1** [comment]
@taniarascia is anyone on this issue?  I could take a look but not if anyone is already actively developing

**Comment by taniarascia** [comment]
I started on it. I have mobile displaying the note list currently. I was planning on basically translating either the note to be visible (on click) or the settings sidebar to be visible (on click an icon at the top right), with a “new note” button fixed to the bottom of the main screen. If you want to go for it or have a better idea, feel free, otherwise I’ll work on it soon.

**Comment by taniarascia** [comment]
It's technically responsive now. Will require a little cleanup but mostly taken care of.
