### ISSUE TITLE
[Tests] Use Cypress app actions pattern

### ISSUE THREAD

**Issue by MartinRosenberg** [taniarascia/takenote#133]
Use the [App Actions pattern](https://www.cypress.io/blog/2019/01/03/stop-using-page-objects-and-start-using-app-actions) for testing.

#### See also

- [An official example of the pattern](https://github.com/cypress-io/cypress-example-recipes/tree/master/examples/blogs__application-actions) (unfortunately already compiled to ES5)
- [An almost-official example of the pattern](https://github.com/bahmutov/test-todomvc-using-app-actions) (also already compiled)
- [Adapting it to Redux testing](https://www.cypress.io/blog/2018/11/14/testing-redux-store/)

**Comment by taniarascia** [comment]
I don't see this happening any time soon, so I'm postponing it.
