### ISSUE TITLE
Electron Offering?

### ISSUE THREAD

**Issue by aequasi** [taniarascia/takenote#137]
Would be pretty slick to get this as a desktop app, with a built-in db (sqlite?)

**Comment by taniarascia** [comment]
Would be, but it is outside of the scope of the current project.

**Comment by mjpowersjr** [comment]
Are you familiar with the [Notable](https://github.com/notable/notable) project on github? Integration between the two projects seems like it would be really nice!

**Comment by aequasi** [comment]
I was not. Thank you.

I’m not sure how that’s out of scope, but that is a bummer.

**Comment by MartinRosenberg** [comment]
@aequasi The current scope of the project is a web-based note-taking app that stores everything to GitHub Gists. Desktop app is at least currently out of scope, and using a database is a totally different design goal.

**Comment by aequasi** [comment]
Electron just wraps your web-based app, and a database was an on-the-side suggestion. Using electron wouldn’t prevent you from still using gists

**Comment by jasontmiani** [comment]
I can put something together for this!
