### ISSUE TITLE
Note list + Note editor has weird issues

### ISSUE THREAD

**Issue by Publicker** [taniarascia/takenote#139]
## Current Behavior

1. Title of note is not showing clearly (sometimes a part of the title and sometimes an empty title)
2. Preview Note is not seeing it in Dark mode (letters are black so as the background)

## Attachments
![cake-ingredients](https://user-images.githubusercontent.com/52673485/67144502-74f30d00-f24d-11e9-8bc6-7424f923c63d.gif)
![not-working-properly](https://user-images.githubusercontent.com/52673485/67144528-b2f03100-f24d-11e9-9d96-0af134aee234.gif)
![preview-dark-mode](https://user-images.githubusercontent.com/52673485/67144631-0151ff80-f24f-11e9-9cd9-bfb0cedc2420.gif)

## Possible Solution
I think that maybe there was a conflict doing a merge and some changes were overwritten.
Why do I think this? Because the point `2` (see list above) it had already worked (please see the [preview](https://5da9e71837a811000aad3b6b--tnote.netlify.com/) of pull request #119 generated by Netlify).

Steps to reproduce in master and preview of #119 
1. Create a note (with or without markdown) 
2. Enable `Dark Mode`
3. Enable `Preview Note`

## Another curiosity
There is something weirder, in localhost-master (dev mode) the issues about `Note Title` are other (I just did a `git pull`).

1. The title is not just the first line of the note. Now, the title takes the first lines of the note.
![i-am-the-title](https://user-images.githubusercontent.com/52673485/67144848-f2b91780-f251-11e9-991b-b392dfe24d33.gif)

This makes me think that maybe is an error occurred when deploying to Netlify

**Comment by taniarascia** [comment]
- Fixed preview in dark mode
- Fixed characters not showing in title
- Fixed multi line titles

Will need a better solution for other lang chars.
