### ISSUE TITLE
Ability to remove all notes from trash at once. 

### ISSUE THREAD

**Issue by VolodymyrKlimov** [taniarascia/takenote#143]
It would be nice to be able to empty trash clicking on one button. Deleting every note separately can be annoying.

**Comment by siliconeidolon** [comment]
I'm looking at this 👍

**Comment by iambenkay** [comment]
@siliconeidolon Are you already working on this. I am looking at taking it up.

**Comment by siliconeidolon** [comment]
I am working on it.

**Comment by taniarascia** [comment]
Closed in #146

**Comment by taniarascia** [comment]
@all-contributors please add @siliconeidolon for code, bug, tests
