### ISSUE TITLE
Highlight drop area on hover for categories and folder

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#153]
Right now, there is no indication that an area is droppable. The folders or categories should be highlight on drag over so indicate that they are a dropzone.

**Comment by noobyogi0010** [comment]
Hi @taniarascia !
I would like to work on this. 
Thanks.

**Comment by harrySullivan** [comment]
I think I've done it.
#162

**Comment by taniarascia** [comment]
#162 covers categories, will just need to copy that code over to the other folders.

**Comment by harrySullivan** [comment]
#164 This seems to have made drop coloring for both favorites and trash.

**Comment by taniarascia** [comment]
Closed in #162 and #164
