### ISSUE TITLE
Consider creating a Spectrum chat community?

### ISSUE THREAD

**Issue by ctrlplusb** [taniarascia/takenote#154]
https://spectrum.chat

I am so so so stoked to see this project coming to life. THANK YOU!

Was wondering if it was worth creating a community channel for general discussion?

**Comment by taniarascia** [comment]
Hi! Glad you’re interested in the project. I do have a Slack channel that can be used for discussion: [HTTPChat](https://join.slack.com/t/httpchat/shared_invite/enQtNzk5NTY0MDMxMDg5LWI2NTg0NjQ4YjAxOGI3OWFkZDZiYTdmOTA1OGU0ZjY3NmRkOGJkMzIxOTAyMzU0YzdiZGQyMjg5MjY4MTJhMjE)

**Comment by taniarascia** [comment]
I did make one - https://spectrum.chat/takenote.
