### ISSUE TITLE
[Bug] Using Preview with Dark Mode Makes Text Disappear

### ISSUE THREAD

**Issue by jasontmiani** [taniarascia/takenote#157]
**Describe the bug**
With dark mode enabled, using Preview makes text disappear from the page. This likely stems from the dark mode color (dark grey) and the paragraph text (black) being too similar in color. 

**To Reproduce**
1. Create a note that includes paragraph text. 
2. Enable dark mode
3.Enable Preview toggle
4. Paragraph text no longer displays in the note. 

**Expected behavior**
If you enable dark mode, all text font color should adjust to white or grey

**Screenshots*:
I will add as soon as I can.

**Comment by BenCohenVi** [comment]
I would like to do that

**Comment by taniarascia** [comment]
@jasontmiani I can't replicate the issue in Chrome, Firefox, or Safari, can you provide a screenshot?

**Comment by taniarascia** [comment]
Please reopen if you can provide a screenshot.
