### ISSUE TITLE
Issue with Settings popup close button

### ISSUE THREAD

**Issue by amitmerchant1990** [taniarascia/takenote#168]
Hey,

While navigating through the application, I've opened up the "Settings" model and while looking into it, I've found this small issue with the "Close" button of the popup. What is happening here is, I'm not able to close the popup by clicking anywhere on the button including the edges(which is the intended behaviour) but instead you specifically need to hit the "X" inside the button which is a relatively small area and that can create the sense of sluggishness among the users if they can not close the popup in multiple tries.

I looked into the code and found that we can mitigate this issue here https://github.com/taniarascia/takenote/blob/master/src/containers/SettingsModal.tsx#L66 by replacing the following 

```jsx
<div className="action-button">
    <X
        size={20}
        onClick={() => {
        if (isOpen) {
            _toggleSettingsModal()
        }
        }}
    />
</div>
```

To this

```jsx
<div 
    className="action-button"
    onClick={() => {
        if (isOpen) {
            _toggleSettingsModal()
        }
        }}
>
    <X
        size={20}
    />
</div>
```

i.e. To move the click event to the surrounding div. I believe this will fix this issue.

Let me know what you think about it.

Regards!

**Comment by taniarascia** [comment]
Sounds good to me. Want to make a PR?

**Comment by amitmerchant1990** [comment]
Sure! I'll work onto it.

**Comment by Dantaro** [comment]
@amitmerchant1990 any movement on this?
