### ISSUE TITLE
Allow escape key to exit settings modal

### ISSUE THREAD

**Issue by Dantaro** [taniarascia/takenote#170]
**Hitting esc on settings modal does nothing**
Currently the settings modal can only be closed using the X, which can be scrolled away from on sufficiently small screens (Such as laptops), or by clicking outside the window, which requires the use of a mouse.

**Allow esc key to close modal**
Hitting esc should cause the modal to close, releasing the user from it's grasp and saving us from the sick requirement of the mouse.

**Comment by pigcake999** [comment]
I agree should be a feature

**Comment by ashinzekene** [comment]
I'd pick this

**Comment by Dantaro** [comment]
I've put in a PR to add this: #171

**Comment by taniarascia** [comment]
Closed in #171
