### ISSUE TITLE
[Feature] Add logged out mode

### ISSUE THREAD

**Issue by Dantaro** [taniarascia/takenote#172]
Currently, the system uses github to log in and store data, however that requires a callback URL that fails for local / non-takenote.dev URLs.  This is, obviously, not ideal, especially given that the documentation explains that you can run the site using npm start.

We should consider adding an offline-only mode that doesn't sync data to the cloud, but instead just syncs it locally.  This will allow easier local testing and also give people the ability to deploy the app on their own personal sites.

**Comment by papigers** [comment]
What should be done with the front page?

My suggestion is to move the editor to a dedicated path, e.g. `/notes`, that would be accessible to offline users on the front page via a link, and also redirecting users directly to `/notes` after local login.

Thoughts?

**Comment by Dantaro** [comment]
It might be easiest to just have a "log in later" button on the homepage, sign up, and sign in pages that just takes you straight to the app, I don't think we need an entire separate route for it, but I'm open to other opinions.

We'll also likely want to put in some logical divisions in between things that require log in and things that don't so as the logged in features expand we can leave a clear separation.  The last thing we want is to have a ton of spaghetti logic to separate the two states.

**Comment by taniarascia** [comment]
I’ve moved the app itself to a private route at /app, so maybe there could be a /testing route that does not require login and just continues to use local storage.

**Comment by taniarascia** [comment]
I figured out a solution to this issue, as seen is #256 . For end to ends tests, I set a test variable `TEST_ENV` to true. If that's running, it will bypass auth and go to different routes. 

```js
const isTest = process.env.TEST_ENV

if (isTest) {
  // Mocked routes for Cypress end-to-end tests
  router.get('/callback', mockAuthHandler.callback)
  router.get('/authenticate', mockAuthHandler.authenticate)
} else {
  // Real routes
  router.get('/callback', authHandler.callback)
  router.get('/authenticate', checkAuth, authHandler.authenticate)
}
```

I feel like this is a relatively clean way to separate real world auth and tests. We'll be able to bypass every single endpoint that connects with GitHub this way! Would be interested in if @codytowstik knows a cleaner way to accomplish this, but so far it's working pretty well.
