### ISSUE TITLE
Add PWA support

### ISSUE THREAD

**Issue by Dantaro** [taniarascia/takenote#173]
Consider finishing off missing features for general PWA compatibility

![image](https://user-images.githubusercontent.com/2750903/68324984-28e9fa00-008e-11ea-9834-04ce184cd849.png)

As listed in the image, there are only a few things needed to finish the general implementation.

The check was generated using Lighthouse

**Comment by papigers** [comment]
![image](https://user-images.githubusercontent.com/5209100/68535407-f6b8f080-034a-11ea-9ccc-b7cd970f79c9.png)

This is the result of the Lighthouse check running on the PR on localhost (hence the HTTPS redirect "error").

**Comment by Dantaro** [comment]
Closed with #179
