### ISSUE TITLE
[Bug] Deleting text in mobile incorrect creates repeat text, and hitting enter/return will return all deleted text

### ISSUE THREAD

**Issue by Dantaro** [taniarascia/takenote#180]
**Deleting text in mobile incorrect creates repeat text, and hitting enter/return will return all deleted text**
Creating text then creating additional text on a new line, then deleting the text, causes odd bugs that result in the text not being correctly removed, and a second hit of the enter/return key recreates all the deleted text

**To Reproduce**
On Mobile:
1) Create a new note
2) Add text
3) Add a new line
  -  Additional note: This will take the text you just wrote to the new line, it looks like the cursor gets reset to the first position of the line.
4) Add more text
5) Hold down the backspace key
  -  Additionally, you might notice the text doubling up or otherwise mixing what you're deleting with what is left on the page
6) Once the text is removed, hit enter/return
7) Note that all the text is returned.

**Expected behavior**
No text should be returned when hitting enter, nor should the other additional errors happen

I'm able to repo this on the most recent android version on a Pixel 3.  Additionally I can reproduce both with the installed PWA and the webapp itself in Chrome.

**Comment by Dantaro** [comment]
Can someone attempt to reproduce this in android and ios? I don't have another android device or an up-to-date ios device to do the testing myself

**Comment by taniarascia** [comment]
Cannot reproduce in iOS (iPhone 7 on latest OS).

**Comment by Dantaro** [comment]
Here's a video of the bugs in question on Android (pixel 3)

**Comment by Dantaro** [comment]
![Takenote_180_gif](https://user-images.githubusercontent.com/2750903/68674170-f66f4f80-051a-11ea-9aa3-12d123647eca.gif)

Here's a gif of the bugs in action

**Comment by taniarascia** [comment]
I think I'm going to remove the mobile version entirely, since Apple has made sure that having a web app on a browser is a no-go by rooming the ability to disable zoom and give an actual webapp-like experience. No mobile code, no mobile bugs. 🙂

**Comment by taniarascia** [comment]
I remove mobile, so this doesn't apply anymore as it won't work on mobile at all. I'll have to figure out a better solution in the future.
