### ISSUE TITLE
Make search field accessible via a keyboard shortcut

### ISSUE THREAD

**Issue by yogan** [taniarascia/takenote#182]
To be able to quickly search for notes, it would be nice to be able to give focus to the search box via a keyboard shortcut (similar to the already existing shortcuts to create new notes, etc.)

Proposed solution: use the shortcut `<ctrl>`+`<alt>`+`<f>` (similar, but not colliding with the common `<ctrl>`+`<f>` shortcut in browsers).

**Comment by yogan** [comment]
There is a preliminary PR #181 for this feature request.

**Comment by taniarascia** [comment]
Closed in #181.
