### ISSUE TITLE
[Feature] Server side storage?

### ISSUE THREAD

**Issue by arpieb** [taniarascia/takenote#188]
In addition to the issue open re GitHub storage (#165), would it be possible to integrate a server-side storage solution?  I'd like to be able to host my own personal TakeNote server that I could access from different computers, which seems like a natural extension for a web-based app.

Thanks!

**Comment by taniarascia** [comment]
@arpieb I would prefer not to store any sensitive data myself - I want to leave that to GitHub. You could set up the app to connect to your own local database instead of GitHub...I don't think the majority of people want to set up their own hosting for TakeNote, though.

**Comment by taniarascia** [comment]
Going to go with just GitHub for now. Will consider an alternate form in the future.
