### ISSUE TITLE
[Bug] Signup and login pages say "Log in to taniarascia"

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [taniarascia/takenote#189]
**To Reproduce**

1. Log out of TakeNote if you're already logged in.

2. Click Log In **or** Sign Up.

3. Note the text under `Welcome`.

**Expected behavior**

I'd get rid of the text altogether and just keep the Welcome and the button underneath. Otherwise, you could say "Log in to continue," but that would be redundant.

If you plan on adding more login options in the future, you could get rid of "Continue with GitHub" and just say "GitHub." That way, you could use "Log in to continue" or some other welcome text.

**Screenshots**

![image](https://user-images.githubusercontent.com/19352442/70366258-05b89300-1864-11ea-91b2-ea04deb0a16b.png)

**Comment by taniarascia** [comment]
I haven't found a way to change this text yet. It seems to just take the account name.

**Comment by danyalasif** [comment]
> I haven't found a way to change this text yet. It seems to just take the account name.

Do you mean it takes the account name of the currently logged in user or just takes your account name? Maybe I can look into it.

**Comment by AleksandrHovhannisyan** [comment]
@danyalasif It seems to be taking Tania's GitHub username. I think it may be a problem with the authentication service's logic—maybe it's taking the name of the owner for an app, instead of the app name itself? Like, I wonder if the app were under a GitHub organization named `TakeNote`, would that make a difference?

**Comment by taniarascia** [comment]
I'll be rewriting the auth and removing auth0 entirely, so that will get around that issue, but it persists for now because I have no control over it.
