### ISSUE TITLE
[Notes] Add search functionality

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#2]
- Add a search bar (either above the note list, or general app sidebar list)
- Search through all notes

**Comment by alexlee-dev** [comment]
I'll try this one if that's cool.

**Comment by waellerbe** [comment]
> "I'll try this one if that's cool."

@alexlee-dev:     Looking forward to see the implementation of the future search feature.

## Curious  ❔  
Is there any chance that this future feature my pull some concepts from the [GREP](GREP "Powerful CLI resource") command? In the world of Linux, this command is incredibly helpful with our search for information.
