### ISSUE TITLE
[Bug] Make an option to disable npm certificate check

### ISSUE THREAD

**Issue by romgerman** [taniarascia/takenote#201]
**Describe the bug**
If npm cannot verify certificates it fails. I'd like to see an option to disable certificate checking. Because i can't run Dockerfile on my workplace.
To disable ssl check set it in npm config
```
npm config set strict-ssl false
```

**To Reproduce**
Just set up a proxy or vpn that will inject its own certs or something like that.

**Expected behavior**
...

**Screenshots**
```
npm ERR! code UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! errno UNABLE_TO_VERIFY_LEAF_SIGNATURE
npm ERR! request to https://registry.npmjs.org/@babel/parser/-/parser-7.7.7.tgz failed, reason: unable to verify the first certificate
```

**Comment by taniarascia** [comment]
Can you give more information about this? When does it fail?

**Comment by taniarascia** [comment]
Since I can't replicate this and haven't gotten any more details, I'm going to close it. Feel free to re-open this with more details. I just don't know what you're trying to do to get to this error.
