### ISSUE TITLE
Why is the app requesting more permissions access?

### ISSUE THREAD

**Issue by nandorojo** [taniarascia/takenote#202]
<img width="556" alt="Screen Shot 2020-01-09 at 4 18 15 PM" src="https://user-images.githubusercontent.com/13172299/72105550-bdc1db80-32fb-11ea-80ef-11a517531abb.png">

I didn't mind allowing access to gists, but I'm not sure how this other info is all relevant for a notetaking app. I'm not able to access the app without allowing these permissions, and I'd prefer not to.

Thanks!

**Comment by taniarascia** [comment]
Hello, this app is still in development and I’ve been working on the authentication. It actually does not touch any of your data at any time. I’ll reduce the permissions when I’m back from vacations, but the app is currently not doing anything and isn’t even set up to access anything besides your public username and email right now. It will ultimately only request repo (not gist) access.

**Comment by nandorojo** [comment]
Hey, thanks for getting back to me while on vacation! Feel free to respond once you're back.

I'll jump on the app again once the permissions are updated. Thanks again!

**Comment by taniarascia** [comment]
Just got back, so I fixed it now. Eventually TN will be updated to not use Auth0 at all.

**Comment by nandorojo** [comment]
Thanks again, I’ll try it out!
