### ISSUE TITLE
[Feature] Bring this project to mobile as a pwa or using react native

### ISSUE THREAD

**Issue by jackson-elfers** [taniarascia/takenote#204]
I'd love to use this as a stand-alone app on android mobile.

**Comment by taniarascia** [comment]
I would like to make a mobile app for it, but that will be after the web app is complete.

**Comment by taniarascia** [comment]
I'm going to close this for now, as it's not going to happen until the application itself is complete. PWA does not seem likely, but React Native can definitely be a "second phase" item.

**Comment by jackson-elfers** [comment]
Cool, I'll probably help out further down the road when the time comes. Great work so far, have a good one. JE

**Comment by taniarascia** [comment]
That would be awesome!

**Comment by amatiasq** [comment]
Just a question: why is PWA discarded?
