### ISSUE TITLE
Consider Limited Permission for GitHub signin.

### ISSUE THREAD

**Issue by 0xApp** [taniarascia/takenote#205]
When trying to login via GitHub account, the existing OAuth list of access requested is way too much, which might be idea.

![image](https://user-images.githubusercontent.com/4899586/72665449-a89d2900-3a2e-11ea-8954-c87af23392cf.png)

Please consider limited access for sign in.

**Comment by taniarascia** [comment]
This whole thing is being rewritten so it will no longer use Auth0, but it should only be requesting repo permissions and nothing else. Can you check again?

Here’s the permissions in the Auth0 setup.

![08D5EFEE-0E03-47EF-8907-5A2FBF905F2F](https://user-images.githubusercontent.com/11951801/72666995-e709f800-39dc-11ea-8903-d200cacc89af.png)

**Comment by 0xApp** [comment]
@taniarascia Thanks for such a quick response.

It is still asking the same 
![image](https://user-images.githubusercontent.com/4899586/72668002-0d18b200-3a48-11ea-851b-08d548478b6d.png)

**Comment by taniarascia** [comment]
I'm sorry, I don't know why it's doing that. I set it to only repo, so I'm not sure what else I can do. The app physically does not have the capability to touch any of those things even if I tried, but I can see why it's disconcerting. Soon Auth0 will be removed so I'm not going to spend more time trying to figure it out.

**Comment by taniarascia** [comment]
Looking further into it, it is only requesting repo. This is the smallest amount of permissions I can request for private repo access. I would prefer to request less but it is not possible.
