### ISSUE TITLE
[Feature] Add GitHub authentication

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#207]
Re-do authentication, without Auth0. See #203.

**Comment by obedparla** [comment]
Hey Tania, 

Not sure if related, but I logged back into takenote after the Auth change and my progress for about 2k words was lost. It seemed to have the state I left it on on my visit previous to my last.

Luckily I had it saved somewhere else, but leaving this note here in case it helps. Not sure if it can be reproduced.

**Comment by taniarascia** [comment]
Sorry about that 😔 Unfortunately, it’s saving all state in local storage right now, and it’s not stable or safe to make it your only source of data. Even if I do nothing and Chrome updates, it can delete your data. Until this GitHub integration is complete, please make sure to back up your data!

**Comment by obedparla** [comment]
Thank you! Yeah I figured it was related to local storage messing up 😅 , that's why I always made sure to save it somewhere else before finishing a session. 

Thank you for the great work on this tool so far!

**Comment by codytowstik** [comment]
Is there no login page now sice github auth is in progress?

**Comment by taniarascia** [comment]
Yes, but I do have a branch I can push up so you can see the progress. It’s moved to a dual server/client system instead of only front end. I just can’t merge it in until I move to a new host since Netlify is front end only.

**Comment by codytowstik** [comment]
Cool, happy to take a look :+1:

**Comment by taniarascia** [comment]
It’s on this brand at the moment until I get a CI pipeline set up: https://github.com/taniarascia/takenote/tree/initiate-express-server

**Comment by taniarascia** [comment]
TakeNote is officially up and deployed on the Express server, so now it's just a matter of implementing oAuth2. See #213.

**Comment by taniarascia** [comment]
Missing some config in the Travis build so I put up an old version for now.
