### ISSUE TITLE
[Refactor] Comments to explain some decisions

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#212]
Without reading the specific commit messages which implemented a segment of code, it's hard to understand why some things are being done.

I think we should err towards brief comments for on-obvious code to make it easier for more people to start contributing and future proofing segments of code that need it.

**Comment by taniarascia** [comment]
That’s a good idea, however I would classify this as a refactor and not a bug. Are there any areas in specific you think need to be commented first?

**Comment by codytowstik** [comment]
I think mostly around where initialization is going on and around some conditionals that alter behavior... mostly just a continued effort going forward would be fine. I'm adding some as I commit.

**Comment by codytowstik** [comment]
I'll just point out where I think comments would be nice in future PRs.
