### ISSUE TITLE
[Feature] Organizing notes - sort by various characteristics

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#220]
Classic sorting notes:
- Alphabetically
- By creation date
- By last updated date

**Comment by danyalasif** [comment]
If nobody is working on this already, I can look into it. :)

**Comment by codytowstik** [comment]
Go for it! It’ll need a new UI element, too.

**Comment by taniarascia** [comment]
A dropdown in the settings alongside line preview, color theme, etc. should be sufficient for the UI. We can have "last updated" as the default sort characteristic. This will be a good opportunity to clean up the sorting, since it's a bit scattered throughout the app.

**Comment by btpschroeder** [comment]
I'll take this on next week if nobody has done it by then!

**Comment by danyalasif** [comment]
> I'll take this on next week if nobody has done it by then!

Hey, you can take this. I tried working on this but the project fails to run on my Windows PC, and I am having trouble with Docker, which is why I have been unable to work on it. Sorry for the delay guys.

**Comment by taniarascia** [comment]
Interesting, I’ll look at Windows local setup soon.
