### ISSUE TITLE
[Refactor] Landing page improvements

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#225]
The landing page was made quickly and needs some improvements.

- Add a footer, linking to GitHub, bugs/issues, potentially with a link to DigitalOcean should they wish to sponsor the app
- Improve copy (I'm not great at selling things)
- Add copy about technologies used in the project (TypeScript, Node, React, Redux...)
- Take a new screenshot with updated styles
- Probably add a screenshot of dark mode somewhere
- Optimize images

Probably some other things I haven't considered that could make it better.

**Comment by vincentdoerig** [comment]
![image-slider](https://user-images.githubusercontent.com/24668338/73776304-ca651280-4787-11ea-8d3c-3537a241b0a5.gif)
I think a comparison slider like this would work pretty well to show light/dark mode.

**Comment by codytowstik** [comment]
That’d be pretty cool imo!
