### ISSUE TITLE
[Tests] More tests for different features

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#228]
**Problem**
The more complexity we add, the more vital testing each part of code is. Also, writing tests is a good way to get familiar with the functionality of the code! See existing `.test.tsx` files for examples.

**Suggested Unit Tests**

- [ ] Settings
- [ ] Functionality used in `dispatch()` methods

**Suggested end to end Tests**

- [ ] Settings

    - Active line highlight
    - Markdown Preview
    - Dark Mode
    - etc...

- [ ] Keyboard Shortcuts

**Note**
Please comment on which test you are adding, and create new files if it makes sense.

**Comment by taniarascia** [comment]
Going to close this for now and come up with granular list of features and functionality to add tests for.
