### ISSUE TITLE
[Feature] Markdown menu

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#229]
**Problem**
It is boring to type out some types of Markdown, having a clickable menu to add markdown at current cursor position or around currently selected text (like the on you see when writing a comment on GitHub)

**Suggested Solution**

When the code editor is in `Edit` mode and the cursor is active in the editor, a menu should appear at the top.

To start, let's start small:

- [ ] Bold
- [ ] Header
- [ ] Code Blocks
- [ ] Unordered List

Stretch goals:
- [ ] Dark mode support
- [ ] Foldable section

**Note**
Don't forget to add tests (e2e and unit) for functionality implemented. Don't forget any resources (icons) used should be public intellectual property.

**Comment by taniarascia** [comment]
Are you referring to creating a WYSIWYG type editor, or buttons that will format your text? If that's the case, I generally do not support adding this feature, because I want this to be a plain-text note-taking application that just happens to have markdown previews and syntax highlighting. 

Generally, I would prefer not to have any functionality regarding the actual typing beyond what you might encounter in a coding IDE - nothing that formats for you without you typing it in. The only exception I could imagine is if you type the beginning of a list item and press enter, it could assume you're continuing that list unless you press enter twice.

**Comment by codytowstik** [comment]
The buttons wouldn't format your text explicitly (WYSIWYG), they would just add the proper markdown... only available in `Edit` mode

So if I am on a new line and click the `Bold` menu option, it would insert `**<cursor is here now>**`

Or if I highlight `this word` then it would do something like `**this word**<cursor is here now>` like an IDE would allow 'surround with'

For simple markdown like bolding, this is nice as it allows for rapid note taking (watching a video, reading a document, watching a lecture) and then easy reformatting.

For more complex markdown, it's hard to remember the syntax (and often hard to type).

It could even be in a toggleable dropdown menu (settings?) so it doesn't have to take up space.

**On that note** I opened a bunch of issues as suggestions, feel free to comment/close any that don't align with the goals of this project!

**Comment by codytowstik** [comment]
Maybe that would be another feature, as you suggested.. auto completing elements like a list or pressing tab when you are in a bolded element to get out of it (`**hello<cursor is here>**`) -> `Tab` -> (`**hello**<cursor is here>`)

**Comment by taniarascia** [comment]
I'll definitely go through them when I have a chance, thank you! This was just the one that stuck out to me on a glance that we might not want. I guess it could potentially be an optional feature for someone who would want to use it. I do think the automated list making would be helpful.

**Comment by mikelehen** [comment]
It sounds like you explicitly don't want WYSIWYG editing, but in case you change your mind, ProseMirror seems to [support it](https://prosemirror.net/examples/markdown/) nicely.  I believe it also has good mobile support (works in iOS and Android for me), which could help solve #246 (wouldn't have to resort to a readonly mode).  Just food for thought.

**Comment by taniarascia** [comment]
@mikelehen Thanks for the suggestion. This library looks good for a more user-friendly, less developer-familiar type of writing environment. Interestingly, It seems like [ProseMirror actually embeds CodeMirror](https://prosemirror.net/examples/codemirror/) for code blocks. My aim for TakeNote was a single, cohesive editor that feels like an IDE, though. Might be good to play around with and see if it plays better on mobile, but I don't think any fully web-based solution will be very good on mobile.

**Comment by taniarascia** [comment]
Closing this one out for now unless there's a big demand for it. I think of TakeNote files as more plain text than markdown, and TakeNote as more of an IDE type editor than Markdown editor.
