### ISSUE TITLE
[Feature][Documentation] Create example document that has markdown supported by Takenote

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#230]
**Problem**
All markdown rendering engines support different kinds of markdown in different ways. We should create an example document that shows features we can render.

**Suggested Solution**
Create a document with a bunch of different markdown that properly renders in the Takenote code editor.

In the future (or as a stretch of this issue), maybe we could have a little question mark at the bottom right that a user can click on to see a document like this.

**Note**
It would be nice to have tests written for each markdown syntax that is in the example, but as v1 of this issue it would be enough just to have the document available in the repository.

**Comment by taniarascia** [comment]
It sounds like this can just be combined with the welcome note.
