### ISSUE TITLE
[Feature] Bulk actions on notes

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#231]
**Problem**
Organizing a lot of notes is hard when handling one by one.

**Solution**
First:
- [ ] Add ability to multi-select notes and drag them into a category (or All Notes, Favorites, Trash)

Stretch
- [ ] New UI element with menu to do a bulk action on these notes (Move to Trash, Favorite, etc)
- [ ] Multi select categories and delete (with new UI element)
- [ ] Multi select categories and drag to trash

**Note**
Accompany added functionality with tests, and prefer comments for any complex logic

**Comment by taniarascia** [comment]
Good idea. It would be useful to be able to bulk delete or change categories.

**Comment by santosh1357** [comment]
I would like to work on this task. Here is what can be one way to achieve it .
1. For each note item, inside div "note-title", add one radio button just like note-options.
2. Write a radio button handler function that will call already working note-options handler for each note, only if more than one notes are selected.

I will try to implement this to see if this work, Kindly let me know in case of any comments or suggestions.

Thanks

**Comment by Mxchaeltrxn** [comment]
I can do this one
