### ISSUE TITLE
[Feature] Custom sorting notes

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#233]
Need to wait for https://github.com/taniarascia/takenote/issues/220 to be completed.

**Problem**
Being able to put notes in a self-defined logical order is immensely valuable for organizing notes

**Suggested Approach**
- Add a `Custom` sort option to the sort UI that should be added in the issue linked at the top
- Initial state of custom sort should be that of the previously selected sort (at least for now)

When Custom sort is enabled

- Ability to drag note in between other notes, this should somehow be persisted wherever notes are stored, which will eventually be Github gists but is currently localStorage

**Note**
- Unit tests for at least loading a set of notes in order
- E2E test making sure order is correct and persists after a refresh

The more tests, the merrier!

**Comment by taniarascia** [comment]
I think the four automatic sorting options gives a good amount of customizability to note sort display for now, so I'm going to close this one.
