### ISSUE TITLE
[Feature] Support moving folders around

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#234]
**Problem**
When creating a new category that is related to another one or is more important than a different category, it is nice to be able to logically organize them.

**Suggested Approach**
Allow categories to be dragged in between (or above/below) another category to change the order. This should be persisted on refresh.

**Note**
- Testing that order of categories is persisted on refresh (after sync)

**Comment by Jfelix61** [comment]
I'll be looking into this, perhaps using a [drag and drop library](https://github.com/atlassian/react-beautiful-dnd).
