### ISSUE TITLE
[Feature] Multi-level categories

### ISSUE THREAD

**Issue by codytowstik** [taniarascia/takenote#235]
**Problem**
Organizing related notes within sub-categories is essential for keeping semantically related notes together but separate

**Suggested Approach**
Ability to add a category under another category, or add a note to multiple categories.

**Note**
- We need to consider the UI behavior of the sidebar when there are too many levels to display
- If a category of the same name is dragged in, what happens? Do we append something like `(1)`?

**Comment by taniarascia** [comment]
I think about notes and categories like this:

- Categories: One (category) to many (notes)
- Tags: Manu (tags) to one (category)

While writing this, I just decided on categories for simplicity, because if I could only have one I'd choose categories. I would propose, if anything, a tag system in addition to categories as opposed to multi-level category hierarchies.

**Comment by codytowstik** [comment]
Ah I was thinking of categories like folders. One category to many (notes | categories) just like a standard file system.

I'm trying to think how I would categorize something like:

I have a set of notes for work, school, and hobbies (three categories) and then for work I have a sub-category for each of the three features each with three stories.

So with how you described it I might:
- Make nine categories for work
- Tag them
1. work, feature 1, story 1
2. work, feature 1, story 2
3. work, feature 1, story 3
...
9. work, feature 3, story 3

- Make nine categories for school
- Make nine categories for hobbies

Resulting in a huge flat list with a large set of tags.

**Comment by taniarascia** [comment]
I'm just thinking if you can nest categories, how much nesting can you do? Infinite nesting? Would it be easy for the UI to handle that? I think adding tags solves the problem without having to worry too much about that, while satisfying the second part of your suggested approach ("or add a note to multiple categories" - in this case, add a note to multiple tags). Perhaps adding tags and allowing one level of sub-categories would be sufficient.

**Comment by Mxchaeltrxn** [comment]
@taniarascia @codytowstik 
A tag system makes sense to me. We can add tags within each file and then we can add a 'Tags' option beneath 'Categories'.

Question(s) about the implementation:
How are we tagging each note? A note taking app called 'Bear' does this with this syntax #tag—any text written with a # next to it will be deemed a tag. If we do something similar, I was thinking of using regex to search for this (and then update the tags option) whenever you focus on a different note (search in the note you were just in) or when you sync (search in the current note).

**Comment by codytowstik** [comment]
I think a tag system would be a good approach for clean and simple organization :)

**Comment by Mxchaeltrxn** [comment]
@taniarascia I just thought about this again. I must have misread your description. I think a simple implementation would be to add an 'add tags' field to the category context menu. Tags can then be viewed within the category by clicking on the category icon. I think it would be useful to display the tags a note is associated with a note in the editor. 

Perhaps creating a component that can be hidden/expanded that holds frontmatter data (or just the tags) that sits above the editor is the way to go? When you expand it, the editor shrinks in height and when you hide it, the editor looks like it does currently.

**Comment by taniarascia** [comment]
I'm going to close this ticket in favor of potentially adding a tag system.
