### ISSUE TITLE
[Bug] List Dropdown Icon Not Clickable

### ISSUE THREAD

**Issue by KonradStanski** [taniarascia/takenote#236]
**Describe the bug**
In the note list, if you open the note option and click on the icon next to add to favorites, instead of adding it to favorites, it moves the dropdown down and to the right.

**To Reproduce**
See Description.

**Expected behavior**
It should add it to favorites instead of moving the dropdown

**Screenshots**
<img width="704" alt="Screen Shot 2020-02-05 at 3 06 23 PM" src="https://user-images.githubusercontent.com/38778413/73887590-161bc880-4829-11ea-9bbd-de1311b932db.png">

**Comment by 1ba1** [comment]
Hi @taniarascia, 

I gave it a shot and I came out with a workaround, more than a real fix, for this issue.

Since the problem is triggered by the icon of the context menu item, I've just added a css class to it and set the pointer-events property to none.

This resolves the issue but I'd like your opinion before I submit a PR.

Thanks for reading.

V

**Comment by taniarascia** [comment]
Hmm, yeah, you're right, that's kind of a band-aid for the issue. The real issue is that there's some sort of click event inception going on, where it's doing the same behavior for the "favorites" icon as it does for the three-dots menu icon.

**Comment by codytowstik** [comment]
In `NoteOptionsButton.tsx` we can add a class to the icon `<IconCmp className="button-icon" size={18} />`

and in `_buttons.scss`
```
.button-icon  {
  pointer-events: none;
}
```

That should work, I think.

**Comment by codytowstik** [comment]
There is another instance of `IconCmp` in `AppSidebarAction.tsx` we should probably give that class, too.

**Comment by codytowstik** [comment]
I think the `handleNoteOptionsClick` is doing the intercepting.

With your fix @1ba1 as the correct approach (imo), we can then fix the 'actual' issue with:

```
if (
      event.target instanceof Element &&
      (event.target.classList.contains('note-options') || event.target instanceof SVGElement)
    ) {
```
to
```
(event.target instanceof Element && event.target.className === 'note-options')
```

**Comment by taniarascia** [comment]
I created a class for elements that should open the context menu, with an edge case for the SVG element, which should ensure that no element that is not explicitly set should be at risk of opening the context menu.
