### ISSUE TITLE
[Feature] Add Split Panes

### ISSUE THREAD

**Issue by KonradStanski** [taniarascia/takenote#237]
I believe that it would be good to add minimal and unintrusive split pane support to allow resizing of the notes list and main side bar.

I believe this would work well with react:
https://www.npmjs.com/package/react-split-pane
https://tomkp.github.io/react-split-pane/#/multiple-vertical

**Comment by taniarascia** [comment]
To me, split panes makes the most sense for the editor itself, as the ability to have multiple notes open at the same time in tabs, but that's also adding a lot of complexity. I do think a simpler approach to the sidebar issue is to have the main app sidebar be collapsible, to start, as I don't think that one needs to be resizable. The notes list might benefit from resizing.

**Comment by taniarascia** [comment]
Finally got around to doing this!
