### ISSUE TITLE
docker pull [Bug]

### ISSUE THREAD

**Issue by ahmdtalaat** [taniarascia/takenote#241]
**Describe the bug**
not sure if this is a bug or not, but on Arch/Linux
when I try to pull the docker image, I get this error "latest not found: manifest unknown: manifest unknown".
**To Reproduce**
run docker pull taniarascia/takenote
**Expected behavior**
I expected to pull the docker image successfully.
**Screenshots**
![Screenshot_20200207_183126](https://user-images.githubusercontent.com/46477493/74046890-127a7400-49d8-11ea-886c-7a87e3e6024e.png)

**Comment by ahmdtalaat** [comment]
Note:
I can pull the image by adding a tag `docker pull taniarascia/takenote:c1cda9e`

**Comment by taniarascia** [comment]
There is no image for `taniarascia/takenote` that has a tag of `latest` on Docker Hub.
