### ISSUE TITLE
[Feature] Add Scratchpad

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#248]
**Problem**
I'd like to have one place for just random things I need to jot down and daily to-dos.

**Suggested Approach**
A main section of the sidebar, along with "All Notes", "Favorites" and "Trash" called "Scratchpad" that only has one note. That way, it's very easy to find this note of randomly jotted content. Name is debatable, but it's the best one I thought of so far.

**Comment by Mxchaeltrxn** [comment]
I can do this

**Comment by taniarascia** [comment]
Closed in #280
