### ISSUE TITLE
Add Screenshot to Readme

### ISSUE THREAD

**Issue by niderhoff** [taniarascia/takenote#26]
Hello and thanks for your project,

I think it would be a nice touch to have a screenshot of how the note taking app looks and maybe some features explained in the Readme.

**Comment by taniarascia** [comment]
Definitely need to do this. Will do once I get the styles in a better place.

**Comment by waellerbe** [comment]
@taniarascia  I would like to volunteer to assist with the future production of screenshots for your project. If it would be of any value, I could also help to annotate screenshots for use in future documentation.

**Comment by taniarascia** [comment]
Sounds good! You can feel free to put one up now, and it can be updated later...I'd say the styles are 75% there...
