### ISSUE TITLE
[Feature] :latest tag on DockerHub

### ISSUE THREAD

**Issue by rinukkusu** [taniarascia/takenote#263]
**Problem**
I've noticed there already was this issue #241 regarding the `latest` tag and it was solved by using an explicit tag. Now I just wanted to use this in my Unraid setup, but Unraid always tries to pull `latest` by default, which still doesn't exist. If I use that specific tag, I lose the ability to update the container later on and have to remove and create a new one, again specify the repository with the new tag and also set all the other variables.

**Solution**
Maybe add a build step in your CI pipeline to also push to the `latest` tag? Please? :smile_cat: 

**Notes**

**Comment by taniarascia** [comment]
Closed in #264
