### ISSUE TITLE
[Refactor] Remove Lodash and Moment

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#272]
Lodash is only used in one file, and moment is only used to set the date of the note being created or synced.

**Comment by jackson-elfers** [comment]
Hey Tania, I got this! What should _.debounce and _.escapeRegExp be replaced with? And it appears moment is being used in multiple files, should we keep it or replace with a native solution?

**Comment by taniarascia** [comment]
Keeping this open since moment is still in there, merging the PR closed this issue by default. Moment is being used in two ways I think, but it shouldn't be a big deal to use native code.

**Comment by jackson-elfers** [comment]
Ok cool, thanks Tania!

**Comment by vincentdoerig** [comment]
I'll have a go at removing Moment.js.

**Comment by jackson-elfers** [comment]
@vincentdoerig  That would be great! Thank you.

**Comment by vincentdoerig** [comment]
Is it ok if I replace moment with [dayjs](https://github.com/iamkun/dayjs/) instead (70KB vs 2KB)? If we want to use exactly the same default formatting as moment ('YYY-MM-DDTHH:mm:ssZ'), dayjs would be the easiest solution.

**Comment by jackson-elfers** [comment]
@vincentdoerig Pretty small footprint I'd say go for it. No point reinventing things if it exists.
