### ISSUE TITLE
[Feature] Right to Left

### ISSUE THREAD

**Issue by BothOfUsTogether2** [taniarascia/takenote#278]
**Problem**
I would like to know if it's possible that text will displayed from right to left?
**Solution**

**Notes**

**Comment by taniarascia** [comment]
It looks like Codemirror has an option for RTL (https://codemirror.net/doc/manual.html) so this should not be very difficult. It should just be a settings option.

**Comment by G-Milevski** [comment]
Hi. I have tried to resolve the issue and created PR =)
But I have one question. When the rtl direction is setted should it applies for preview mode.

**Comment by taniarascia** [comment]
Closed in #332.
