### ISSUE TITLE
[Bug] Copy pasting text over itself does not do anything.

### ISSUE THREAD

**Issue by Mxchaeltrxn** [taniarascia/takenote#279]
**To Reproduce**
1. In edit mode in the editor, type a word.
2. Highlight the word.
3. Copy the word (control/command + c)
4. Paste the word (control/command + p)

**Expected behavior**
The word should be 'overwritten' and the cursor should move to the right side of the word and let the user continue typing.

**Notes**
Actual behaviour: nothing happens.

**Comment by miqh** [comment]
This doesn't appear to be a problem related to TakeNote, but rather the `react-codemirror2` dependency.

Specifically, it's due to the following underlying issue—https://github.com/scniro/react-codemirror2/issues/77

**Comment by taniarascia** [comment]
There have been a few small React Codemirror based issues, but I'm not sure there's a better option for integrating React with Codemirror without having to write our own implementation, which would be a whole project of itself 😞

**Comment by taniarascia** [comment]
Used the fix in the issue @miqh linked to above. It works for single cursor, and for multi-cursor, the paste still works, but the multi-cursors aren't persisted, which I don't think is much of an issue.
