### ISSUE TITLE
[Feature] Unable to drag note from 'Trash' to 'All notes'

### ISSUE THREAD

**Issue by Mxchaeltrxn** [taniarascia/takenote#289]
**Problem**
1. I am unable to drag a note from trash to all notes. I feels like this should be allowed.
2. Also I think it's a little strange that 'All notes' doesn't actually mean 'all' (does not contain trashed notes and scratchpad).

**Solution**
1. Enable a note to be restored from trash by dragging it into 'All notes'
2. Perhaps 'All notes' should be renamed to 'Notes'?

**Notes**
I'm not really sure about problem (2) so I added it here instead of making a new issue for it.

**Comment by taniarascia** [comment]
I think renaming "All notes" to "Notes" could be good. I definitely would not want to add the trashed notes to this section, as trash is always understood to be something separate from everything else (as it is with trash for email, or an OS). I wouldn't consider the scratchpad a note, either. 

Adding the ability to drag a note out of the trash should be simple enough.

**Comment by pavlakissimos** [comment]
Hi there,

If nobody is working on this issue i would like to give it a try.

**Comment by pavlakissimos** [comment]
How should we treat favorite notes that are dragged to All Notes category?

**Comment by Mxchaeltrxn** [comment]
@pavlakissimos In my opinion, you shouldn't allow that functionality to happen (the all notes category should seem disabled when dropping a favourited note over it). 

The alternative is that you drop it in all notes and nothing changes. 

Since nothing changes, I think we should go with the first option.

**Comment by taniarascia** [comment]
@all-contributors please add @kodyclemens for code, test.

**Comment by taniarascia** [comment]
Hi @kodyclemens, a bug resulted from this PR: https://github.com/taniarascia/takenote/issues/355.

Would you be able to look and fix that?

**Comment by kodyclemens** [comment]
Sure thing @taniarascia
