### ISSUE TITLE
[Feature] Clicking on the icon of a category should make it drop down

### ISSUE THREAD

**Issue by Mxchaeltrxn** [taniarascia/takenote#290]
**Problem**
Clicking on the icon of a category should make it show the notes inside it. It feels a little strange that it doesn't do that right now.

**Solution**
Add functionality to do that.

**Notes**
To me, this is a low(er) priority feature.

**Comment by taniarascia** [comment]
With the current UI layout, you can already click on a category and see all the notes in the note sidebar, which exists to show all notes within a category. I don't know what benefit there would be to displaying all notes in the note sidebar and the app sidebar, as well. This is something I would prefer not to implement in the UI, so I'm closing this issue.
