### ISSUE TITLE
[Refactor] Update note list to use react-dnd

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#292]
Right now, the categories are using `react-beautiful-dnd`, and the notes are using HTML5 built-in drag and drop. Since we already are using the dependency and it has more features, animations, works on mobile, is more customizable with less custom work, etc, we may as well use it across the board, so no one has to learn two types of DnD.

**Comment by pavlakissimos** [comment]
I'm currently working on this issue but i have encountered a problem. I made the folder options droppables but when i'm dragging a note over an option, the folder option expands to the note's height. This is propably happening because of the ```provided.placeholder```.

Based on [react-beautiful-dnd docs](https://github.com/atlassian/react-beautiful-dnd#not-for-everyone-%EF%B8%8F):

> There are a lot of libraries out there that allow for drag and drop interactions within React. Most notable of these is the amazing react-dnd. It does an incredible job at providing a great set of drag and drop primitives which work especially well with the wildly inconsistent html5 drag and drop feature. react-beautiful-dnd is a higher level abstraction specifically built for lists (vertical, horizontal, movement between lists, nested lists and so on). Within that subset of functionality react-beautiful-dnd offers a powerful, natural and beautiful drag and drop experience. However, it does not provide the breadth of functionality offered by react-dnd. So react-beautiful-dnd might not be for you depending on what your use case is.

I have the impression that this library may not be the best solution for our use case.

Any ideas on how i should procceed or a comment about any misunderstandings i may have about what i mentioned above are welcome.

I have also made a [draft PR](https://github.com/taniarascia/takenote/pull/326) for details about what i've done so far.

**Comment by taniarascia** [comment]
Hi @pavlakissimos,

Hmm, yeah, I think it's calculating the droppable height from the draggable object. I also see this error:

> react-beautiful-dndDroppable: unsupported nested scroll container detected. A Droppable can only have one scroll parent (which can be itself) Nested scroll containers are currently not supported.

No matter how I resize things, it seems to have very buggy behavior. :( It doesn't seem to understand the cursor position for dropping, which is what we need. It looks like you're right, beautiful-dnd is only optimized for lists, not really for dragging into small containers. 

I don't know if using react-dnd would offer any benefits over the current solution...I hate to think that you wasted your time on this PR, but it seems like the current solution is better than beautiful-dnd. What are your thoughts?

**Comment by pavlakissimos** [comment]
Hi @taniarascia,

Sorry for the late response.

I didn't waste my time so don't worry about it ;)

1) I also think that the current solution is better and making the folder option Droppables wouldn't really offer us anything.

2) If we wanted to try react-dnd, i think based on this [codesandbox](https://codesandbox.io/s/wyl6jm7oy7?from-embed) we could make things work. With that we could replace the HTML5 drag & drop API and beautiful-dnd. I could make a branch to test that with the categories list and maybe see if it would benefit us any other way.

**Comment by taniarascia** [comment]
@pavlakissimos!

I'm glad you're not bothered by the setback. Do you think there are any benefits to using `react-dnd`? The one major benefit I can think of is using a consistent API  for both categories and notes. If you want to work on testing it out, let me know!

**Comment by pavlakissimos** [comment]
Hi @taniarascia,

I think with react-dnd we could catch all our drag & drop uses cases. I will test it out and i will come back to you with a response cause I’m not certain yet for some things.
