### ISSUE TITLE
[Feature] Add link to repo

### ISSUE THREAD

**Issue by siliconeidolon** [taniarascia/takenote#294]
**Problem**
Currently there's no way to learn more about the project, raise issues, or ask for features after logging in. 
**Solution**
There should be a link to the repo somewhere in the app after logging in. 

**Notes**
Maybe on the settings pane, or simply a link to the repo or an 'about' popup on the sidebar.

**Comment by NdagiStanley** [comment]
Just to clarify, the link to the repo is on the landing page: (both at the top and the bottom 👇 )
<img width="318" alt="Screenshot 2020-04-19 22 51 35" src="https://user-images.githubusercontent.com/15629602/79698241-561f1300-8290-11ea-930f-9246d73ef924.png">

This feature add is to have it on the app, right?

I would suggest it probably on the side navbar just above the sync.

**Comment by Retnuh1337** [comment]
I have created this feature and I have requested a Pull Request.
