### ISSUE TITLE
Add dark theme

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#3]
And it better be New Moon.

**Comment by joseph-perez** [comment]
I can try and take a shot at this if that's cool Tania 🙂

**Comment by joseph-perez** [comment]
Hi Tania,

I was wondering if I could get a little clarification on this. I'm learning as I go along on this so apologies for the little extra guidance 😅. 

So for the dark theme, you want the theme to be based on these colors? https://github.com/taniarascia/new-moon#colors

And I was looking at how you added a dark theme to your personal site, would you want me to implement the theme kinda the same way you did there but of course all redux based?

https://github.com/taniarascia/taniarascia.com/blob/master/src/styles/themes/dark.scss

Thanks again for letting me try and take this issue on 😄

**Comment by taniarascia** [comment]
Haha yes, exactly! However, the actual CSS classes are bound to change because it’s very minimal and MVP right now. Eventually I will make it responsive and I don’t want to put any serious work into CSS until that happens. 

If you want to tackle this, I would suggest adding the theme provider Redux style, as you said, but not actually write any of the dark mode CSS. Just the ability to toggle between them, and add a “dark” class to the body. That way, once the CSS is more finalized, it will already be set up. 

Since settings isn’t set up yet, you could have the dark mode switch happen on a keybinding.

**Comment by taniarascia** [comment]
Sorry for the lack of info, it was originally just a note for myself 😅

**Comment by joseph-perez** [comment]
Gotcha, will do! And no worries at all 😄

**Comment by taniarascia** [comment]
Toggle finished in #28

**Comment by waellerbe** [comment]
Here to **appreciate** the work that has already taken place with the `dark theme`. In my experience with Typora (another Markdown Editor), themes really help to make a difference with the user experience.
