### ISSUE TITLE
Lint imports

### ISSUE THREAD

**Issue by MartinRosenberg** [taniarascia/takenote#30]
@taniarascia's preference is to sort and group imports as follows:

1. Libraries
2. Local imports (absolute, not relative)
3. CSS/side-effect imports

With each group alphabetized by `from`, named imports sorted within their lines, and spaces between the groups.

Right now, there are multiple rule/plugin/preset options for linting imports, none of them quite does the trick right now, they all conflict with each other, and none of them individually is really a desired compromise. However, the hopefully-upcoming merging of benmosher/eslint-plugin-import#1360 should make `import/order` a perfect candidate.

**Comment by taniarascia** [comment]
I would say option 1 is the best of the three. I wonder if you can chain `import/order` and `sort-imports`, but that seems like overkill.

**Comment by MartinRosenberg** [comment]
You can chain... but only by running `eslint` twice.

**Comment by MartinRosenberg** [comment]
Ah, I missed something about using `import/order`: It doesn't move side-effecting (e.g. css) imports at all, because... y'know, side effects. So you still have to order those manually. But you should probably do that anyway, because... y'know, side effects.

**Comment by taniarascia** [comment]
Fixed in #29 

Will revisit after `import/order` has an update.
