### ISSUE TITLE
[Feature] Integrate Gitlab authentication and note storage 

### ISSUE THREAD

**Issue by heyakyra** [taniarascia/takenote#301]
Instead of Gists, Gitlab has snippets

https://github.com/GitJournal/GitJournal takes a more abstract approach by using a git repo itself as storage, which may have some benefits

**Comment by taniarascia** [comment]
Hi! The plan at this point for TakeNote is to store the notes in a repo, as opposed to Gists. Adding support for GitLab will be a nice stretch for the future, but definitely want to get it working for one provider first.

**Comment by taniarascia** [comment]
Going to close this for now as it's not on the immediate roadmap. Will reopen once GitHub sync is done if we want to support multiple Git hosts.

**Comment by juangburgos** [comment]
Awesome tool! +1 for **Gitlab** repo support for note storage-sync please! I am waiting for either [Wiki.js](https://docs.requarks.io/storage/git) or TakeNote to support Gitlab.
