### ISSUE TITLE
[Bug] Dropping a not selected note into a folder, triggers actions for the selected note

### ISSUE THREAD

**Issue by pavlakissimos** [taniarascia/takenote#320]
**To Reproduce**
Select a note from "All Notes" list -> Drag & drop another note in the "Trash" folder

**Expected behavior**
The note that has being tragged should be trashed instead of the selected one.

**Notes**
This happens between "Trash" and "Favorites" folders.
When dropping a note to a category, it works as expected.

**Comment by taniarascia** [comment]
Good catch. It needs to differentiate between an active note and a control + selected note.
