### ISSUE TITLE
[Refactor] Move settings, sync, add note to top bar above note

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#340]
Currently, the following options exist as buttons on the app sidebar:

- Create note
- Sync notes
- Settings 

I don't really like these being here - I'd prefer the standard right hand corner avatar and settings that GitHub, Todoist, CodeSandbox, Slack, etc. use. I also don't like the floating preview/edit button, so I'd move all of the above into one top bar. I would also like to refactor the settings page to allow for more preferences, like prettier.

**Comment by rizwanahmed19** [comment]
Is this issue open for grab?

**Comment by G-Milevski** [comment]
I made investigate and have next proposal.
The context-menu component should be refactoring. The component work only for show points of a node-list. I think render logic of points should be more general and don't have related to place.

@taniarascia  what do you think about it?
@rizwanahmed19 Do you have any progress in the task ?

**Comment by Mxchaeltrxn** [comment]
Hey @taniarascia I'm back! I'd love to try this one but since I don't quite have an eye for design, I'll be making relatively modular pull requests for feedback if that's okay. I'll try and start this weekend 😀

**Comment by taniarascia** [comment]
Hi @Mxchaeltrxn, by settings page I was referring to the settings modal, but it could be made into a page instead of a modal. In any case, any changes to that is outside the scope of this issue so it could be handled elsewhere. Looking forward to any PRs you might make.

**Comment by pg07codes** [comment]
@taniarascia i would love to work on it? and i think the search bar should also be moved to the top bar.  All in all, the top bar will consist of add, sync, settings btn by the right, search in center and  last sync date and time on the left most part
