### ISSUE TITLE
[Help] Setup takenote from source encounter patch-package error

### ISSUE THREAD

**Issue by yccheok** [taniarascia/takenote#348]
Thank you for writing a wonderful tutorial on React - https://www.taniarascia.com/getting-started-with-react/

It makes me feel I want to learn from `takenote` project, so that I can create some "real" application using react.

I try to download master branch source code in Windows 10 environment. I then perform the following setup.

`

    C:\yocto\takenote>npm i

    > takenote@0.5.0 postinstall C:\yocto\takenote
    > patch-package

    patch-package 6.2.0
    Applying patches...

    **ERROR** Failed to apply patch for package react-codemirror2

      This happened because the patch file patches\react-codemirror2+6.0.0.patch could not be parsed.

      If you just upgraded patch-package, you can try running:

        cd patches\react-codemirror2+6.0.0.patc
        patch -p1 -i h
        npx patch-package react-codemirror2
        cd ../..

      Otherwise, try manually creating the patch file again.

      If the problem persists, please submit a bug report:

        https://github.com/ds300/patch-package/issues/new?title=Patch+file+parse+error&body=%3CPlease+attach+the+patch+file+in+question%3E

    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! takenote@0.5.0 postinstall: `patch-package`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the takenote@0.5.0 postinstall script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     C:\Users\yccheok\AppData\Roaming\npm-cache\_logs\2020-08-07T02_38_21_652Z-debug.log

    C:\yocto\takenote>
`

The `2020-08-07T02_38_21_652Z-debug.log` can be found at https://gist.github.com/yccheok/5902982d2485f46e23a66f6938a02ce6

Seem to me `patch-package` is the root cause, but I have 0 idea how to deal with it.

Can you provide me some hint? Thanks.

p/s I cannot find `.env` file after checkout the source code. Should I create that file manually in root folder, then input my CLIENT_ID and CLIENT_SECRET ? Thanks.

**Comment by pg07codes** [comment]
yes you will have to create the .env file as mentioned in the readme on setting up development enviroment
