### ISSUE TITLE
[Feature] Too bad we need Github Account...

### ISSUE THREAD

**Issue by t3r00t** [taniarascia/takenote#349]
**_Hello TakeNote Team !_**

Im looking for a **OpenSource** Note taking WebApp for my team.
And i found this Really Good looking project with Markdown support and nice UI work.

But when i installed it on a docker container i found out that we need a Github account to log-in , that's a **bummer** really 😅 
I would loved to see a simple Login page with User and Password connected to a _MySQL Database_ that would have been alot better 👍 

You could even do both with a small button on the bottom to connect with Github as secondary option.

_This is just a suggestion , I find this project Really cool !_
**Thanks for your time.**

**Comment by comphonia** [comment]
It didn't require a sign up last i saw it, just like [Stack Edit](https://stackedit.io/app). I think it would be better for login to be optional for people who don't need a save feature.

PS: You can clone the repo and take out the auth for your team.

**Comment by taniarascia** [comment]
Thanks, this app isn't finished, but I would prefer not to maintain a database and users. I may remove all auth and make it a static app that does not persist data.
