### ISSUE TITLE
[Refactor] Update all React Toolkit slices to use mutating syntax

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#358]
Use:

```js
state.x = true
```

Instead of:

```js
{
  ...state,
  x: true,
}
```

**Comment by markerikson** [comment]
Note that additional "mutation" could be done here.  For example, in `slices/notes.ts`, there's a number of cases like this:

```ts
    toggleFavoriteNotes: (state, { payload }: PayloadAction<string>) => {
      state.notes = state.selectedNotesIds.includes(payload)
        ? state.notes.map((note) =>
            state.selectedNotesIds.includes(note.id) ? { ...note, favorite: !note.favorite } : note
          )
        : state.notes.map((note) =>
            note.id === payload ? { ...note, favorite: !note.favorite } : note
          )
    },
```

That could potentially be rewritten along these lines:

```ts
    toggleFavoriteNotes: (state, { payload }: PayloadAction<string>) => {
      const toggleSelected = state.selectedNotesIds.includes(payload);
      
      // Can use a `forEach` loop instead of a `map()` - no need to create a new array manually
      state.notes.forEach(note => {
        const shouldToggle = toggleSelected ? state.selectedNotesIds.includes(note.id) : note.id === payload
        if (shouldToggle) {
          // Can directly "mutate" a given note entry
          note.favorite = !note.favorite
        }
      })
    },
```

**Comment by taniarascia** [comment]
@markerikson Thanks for the tip! I went through and only updated the "top level" mutations, but I definitely left a lot of `map` and `filter` where it could be refactored to `forEach`. That looks way cleaner.

**Comment by markerikson** [comment]
Yeah. One of the great things about Immer is that you can grab out nested values, "mutate" those nested values seemingly by themselves, and Immer does all the work of tracking the parents that need to get copied too.  Like, in this case, `note.favorite = !note.favorite` triggers copies of `notes` and `state` automatically.
