### ISSUE TITLE
[Bug] Default active note in each folder should be the top note

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#367]
**To Reproduce**
Create some notes, change the sorting behavior, and move between the folders

**Expected behavior**
In each category or folder, the first note selected should be the note at the top

**Actual behavior**
It varies by sorting behavior

**Comment by machadolucasvp** [comment]
Hello @taniarascia, can you explain what you mean by defualt active note?

**Comment by taniarascia** [comment]
@machadolucasvp When you click on "Notes" or "Favorites", the first not selected should be the one at the top.

**Comment by machadolucasvp** [comment]
Got it, thanks for answer @taniarascia. I want to work on this, can you assign me ?

**Comment by taniarascia** [comment]
Feel free to work on it, @machadolucasvp. I don't generally assign people to a ticket because often they abandon it, but I don't think anyone else will work on it, and if they do I'll review yours first. :)
