### ISSUE TITLE
[Question] How to persist notes using the docker image?

### ISSUE THREAD

**Issue by cbrgm** [taniarascia/takenote#371]
Hi there,

thanks for this great app! I'm running takenote as a docker image and would like to persist my data using a volume mount.

```
docker run \
-e CLIENT_ID=xxx \
-e CLIENT_SECRET=xxxx \
-e NODE_ENV=development \
-p 5000:5000 \
-v $(pwd):<path??>
takenote:mytag
```

Where does takenote save files within the image?

Cheers
Chris

**Comment by taniarascia** [comment]
Hi there,

TakeNote does not persist anything currently - it's just using local storage.

**Comment by cbrgm** [comment]
Hi there thanks for your fast reply! Is there another way to backup notes?

**Comment by taniarascia** [comment]
This application is still a work in progress. Discussion on GitHub integration and persistence is here: https://github.com/taniarascia/takenote/issues/165

**Comment by cbrgm** [comment]
Interesting! Thanks for sharing! :-)
