### ISSUE TITLE
[Tests] Add end-to-end tests for settings 

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#374]
There are currently no tests for settings. 

List of all settings tests to do:

- [ ] Should open settings menu
- [ ] Should close settings menu on click X or click outside of window
- [ ] Should toggle preferences
  - [ ] Dark mode
  - [ ] Active line highlight
  - [ ] Markdown preview
- [ ] Should change sort order
  - [ ] Last updated
  - [ ] Favorites
  - [ ] Title (Alphabetical)
  - [ ] Date created

**Comment by kodyclemens** [comment]
Going to tackle this one

![](https://media4.giphy.com/media/2wYYlHuEw1UcsJYgAA/200w.webp?cid=ecf05e47dlebdd7jc5du4pg8jrit96vlw46oyxof54in3ka6&rid=200w.webp)

**Comment by JoseRFelix** [comment]
@kodyclemens I can also help with this! Let me know if you need any help.

**Comment by kodyclemens** [comment]
> @kodyclemens I can also help with this! Let me know if you need any help.

Thanks for the offer! I actually just finished up and didn't see this until just now or I would have shared!
