### ISSUE TITLE
[Tests] Add tests for Redux slices

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#383]
Examples exist in `unit/client/slices`.

- [x] Settings
- [x] Note
- [x] Category
- [x] Sync

**Comment by PranjaliPatil14** [comment]
Hello @taniarascia, I would like to work on this issue.  Can you please assign this to me?

**Comment by taniarascia** [comment]
Feel free to work on it! I do not assign tickets to people.

**Comment by PranjaliPatil14** [comment]
Done with the tests @taniarascia. Please review the PR #403 .

**Comment by PranjaliPatil14** [comment]
#403
