### ISSUE TITLE
[Feature] Do not display app on mobile

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#385]
**Problem**
App does not work on mobile. Web browser based application UX will be very poor, so the only option is to eventually make a real native app. But I want to finish the web app before moving on to anything like that.

**Solution**
Display a message upon logging into the application on mobile and/or just don't show the buttons for logging in on mobile.

**Comment by wenderzxavier** [comment]
I would like to work on this :D

**Comment by Jadhielv** [comment]
Done @taniarascia. Check **_PR_**: #402
