### ISSUE TITLE
Change the color or shape of the cursor when using Vim mode

### ISSUE THREAD

**Issue by morbec** [taniarascia/takenote#39]
It is not a bug, just a suggestion. When using Vim mode, It would be interesting, if the cursor change the color (or shape) so we know if we are in the edit mode for example.

**Comment by Publicker** [comment]
I was thinking about how to improve that.

What do you think about changing the cursor to `cursor: alias` (I'm still in doubt of which cursor chose, please see the link below and give me your opinion) and also having a Vim icon at the bottom right?

> Types of cursors [here](https://codepen.io/chriscoyier/full/uCwfB)!

Do you have any idea or suggestion?

If it's cool just assign this to me and I will do it 🐱‍🏍

**Comment by taniarascia** [comment]
This is referring to the two different modes of Vim - default mode and insert mode - not necessarily Vim mode vs. regular mode for TakeNote. I didn’t see any class changes on the DOM when switching, though.

**Comment by Publicker** [comment]
Oh!
I did it a little research and I found it a way to detect when Vim is in insert mode. But I don't know how to go ahead with this information. I will do a PR with that I get it until now and would be pretty cool if you take a look!

**Comment by taniarascia** [comment]
Fixed in #101.
