### ISSUE TITLE
[Bug] Tab children rendered in Tabs are missing their unique key prop

### ISSUE THREAD

**Issue by kodyclemens** [taniarascia/takenote#390]
**To Reproduce**
1. Navigate to app landing
2. Open devtools, active selection should be console
3. Open the settings modal
4. See React warning

**Expected behavior**
The expected behavior is that there should be no React warning regarding unique key props.

**Actual behavior**
React produces a console warning in the dev console due to missing key props on `Tab` children in `Tabs.tsx`.

**Notes**
Easy fix, opening for tracking purposes.

**Comment by roh8raut** [comment]
![Screenshot from 2020-10-22 12-14-51](https://user-images.githubusercontent.com/44293175/96834783-3a274480-1460-11eb-9ac9-483d3eb4e343.png)

Hello @kodyclemens , Did I get the correct SS?

**Comment by kodyclemens** [comment]
@roh8raut this is what I am seeing. I am updated to the latest commit of 4fe8b7af

![](https://i.imgur.com/IGX22cE.png)
