### ISSUE TITLE
[Bug] Downloading notes does not include notes with duplicate title

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#396]
**To Reproduce**
Create two notes with the same title. Download them.

**Expected behavior**
Both notes will download.

**Actual behavior**
It will only download one note with the same title.

**Notes**

**Comment by ModProg** [comment]
What should be the correct handling:
- a.md
-a_1.md
-a 2.md
-a (3).md
-a.4.md
and should they be formatted with zeroes (0001) and if so, should the number of duplicates be counted first to calculate the amount of zeroes?

**Comment by vincentdoerig** [comment]
We could also do it the way MacOS does it:
- file.md
- file (1).md
- file (2).md
- etc.

**Comment by kodyclemens** [comment]
Another option would be to just add a substring of each note's id to each downloaded note's filename. This is simple and prevents the need to find duplicates and keep track of a counter for those duplicates while applying filenames: (1), (2), etc. Note ids are generated from uuid so the chance of collision on an id length of 6 is incredibly low.

```Indexing Strings (a43ed2)``` or ```Indexing Strings-4g3n2j```

**Comment by ModProg** [comment]
I'd prefer the UUID way, this would make sure the name stays the same if it gets moved.

**Comment by ModProg** [comment]
This could also be an option in the settings,

Just have a string where one can write the file name template with `$name`, `$uuid` and `$index`.

Or show a Dialoge when downloading such files.
