### ISSUE TITLE
[Feature] Generate Note from Scratchpad

### ISSUE THREAD

**Issue by ModProg** [taniarascia/takenote#399]
**Problem**
When writing something on the Scratchpad one could want to create a note from everything or just a selection.

**Solution**
There are multiple Solutions I could think of:
1. Creating a context menu entry in the editor, when something is selected `Generate Note from selection` otherwise `Generate Note from Scratchpad`
2. Adding this to the Top-Bar
3. Adding this to the Side-Bar, e.g. dragging the Scratchpad on a Category creates a new Note and new Scratchpad.

**Notes**
- Currently this only takes 3 key strokes (`Ctrl+X`, `Ctrl+Alt+N`, `Ctrl+Alt+V`) so maybe not very urgent.
- What happens to the current scratchpad

**Comment by taniarascia** [comment]
Hi! Thanks for the suggestion. Considering that all you need to do to create a new note from any other note is copy and paste it into a new note, I don't think this feature is necessary.
