### ISSUE TITLE
[Feature] Add import/export to data management

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#411]
**Problem**
There is no way to import data into TakeNote.

**Solution**
In Data Management, add import and export options. Notes and categories should export as a single `.json` file, and you should be able to import that back into the app.

takenote-data.json:

```json
{
  "notes": [],
  "categories": []
}
```

That way, your entire database can be backed up into a single file, and imported into another instance of the app.

**Notes**
I don't think settings is necessary here.

**Comment by JoseRFelix** [comment]
I will tackle this.
