### ISSUE TITLE
Drag and drop: Firefox navigates to www.[noteId].com when note is dropped

### ISSUE THREAD

**Issue by MartinRosenberg** [taniarascia/takenote#42]
See also:

- react-dnd/react-dnd#219
- react-dnd/react-dnd#221

**Comment by jjtowle** [comment]
I think this just requires adding an event.preventDefault() to the drop methods. Will updated tomorrow unless someone picks up first.

**Comment by taniarascia** [comment]
Figured it out - disabled Drag and Drop on Codemirror.
