### ISSUE TITLE
[Question] Travis CI jobs

### ISSUE THREAD

**Issue by kodyclemens** [taniarascia/takenote#420]
I've noticed the Travis CI checks are taking a long time to run. The [current PR](https://github.com/taniarascia/takenote/pull/417) I have open has a job that has been queued for over an hour. Is this normal? I thought that this weekend the job were really fast to be executed. Just opening an issue to be sure something isn't messed up. Travis CI services are all green.

![](https://i.imgur.com/0s6SO5N.png)

**Comment by taniarascia** [comment]
Well, they don't run if the branch is not up-to-date with master. That could be it. Otherwise sometimes Travis just seems to be delayed a bit so I just wait a few hours and it's usually fixed.
