### ISSUE TITLE
[Bug] Remove "Sign up with GitHub" button on mobile

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#426]
**To Reproduce**
View app on mobile.

**Expected behavior**
No "Sign up with GitHub" button

**Actual behavior**
It's there.

**Notes**

**Comment by vincentdoerig** [comment]
I'll have a go at this one.

**Comment by Jadhielv** [comment]
Done @taniarascia. Check **_PR_**: #427

**Comment by taniarascia** [comment]
Can you please refactor the logic here. It does not make sense to check for isMobile in one spot and !isMobile in another spot. This can be simplified. Thanks!
