### ISSUE TITLE
[Feature] TeX Support

### ISSUE THREAD

**Issue by pilleye** [taniarascia/takenote#432]
**Problem**
A lot of my personal notetaking includes taking notes with equations and LaTeX. Would it be possible to include this feature inside TakeNote? Otherwise, looks great.

**Solution**
We could either use [KaTeX](https://katex.org/) or [MathJax](https://www.mathjax.org/) to render math blocks. These blocks could be denoted by `$$` and `$$` as in `$$\LaTeX$$` or a `\(` and `\)`, such as `\(\LaTeX\)`.

**Comment by taniarascia** [comment]
Thanks for the suggestion! I don't really intend to support LaTeX syntax in the application. The app is meant to be very simple and not add a lot of features to address every use case. This would be a bit of work to add complexity into the application for something I personally will never use.
