### ISSUE TITLE
[Bug] Close context menu options after click

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#436]
**To Reproduce**
Click on "Download" or "Copy reference to note" in a context menu.

**Expected behavior**
The context menu will close.

**Actual behavior**
It stays open.

**Notes**

**Comment by machadolucasvp** [comment]
`Remove Category` and `Mark as Favorite`/`Remove Favorite` don't close it either, should they?

**Comment by taniarascia** [comment]
Yes, all context menu buttons should close the menu after being clicked.
