### ISSUE TITLE
[Bug] Github Auth 404

### ISSUE THREAD

**Issue by avevlad** [taniarascia/takenote#442]
.env

```env
CLIENT_ID=87***
CLIENT_SECRET=Iv1.d15c**************
```

![image](https://user-images.githubusercontent.com/2889662/98471665-ff166680-21fe-11eb-8aaa-5c0fff31def4.png)

commit 053fbb27bd3020599679409125d35040d37003c9 (HEAD -> master, origin/master, origin/HEAD)

https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#1-request-a-users-github-identity

**Comment by taniarascia** [comment]
I have no idea what you are trying to communicate here.
