### ISSUE TITLE
[Bug] Unable to open demo 

### ISSUE THREAD

**Issue by iamshouvikmitra** [taniarascia/takenote#449]
**To Reproduce**
Visit https://takenote.dev/app
**Expected behavior**
Should open the web app.

**Actual behavior**
Presented w/ a blank screen with an error in the console.
![Screenshot from 2020-12-02 14-48-49](https://user-images.githubusercontent.com/24479402/100853263-93e24c00-34ad-11eb-9e24-f959e7c165e6.png)

**Notes**
This was my first visit

**Comment by taniarascia** [comment]
Try a hard refresh and deleting local storage? I've only seen that issue for old data in local storage.
