### ISSUE TITLE
[Feature] WYSIWYG Mode

### ISSUE THREAD

**Issue by sirinath** [taniarascia/takenote#457]
**Problem**
In apps like Typora you can work in WYSIWYG mode

**Solution**
Introduce WYSIWYG mode

**Comment by taniarascia** [comment]
WYSIWYG is a feature I specifically do not want for this app.

**Comment by sirinath** [comment]
Can we have a slightly different thing. The page is fully rendered except for the line/element which the focus is on which would be the underlying Markdown. This is not essentially WYSIWYG but as you move the cursor from element/line to line you see the underlying markdown of the new focus element/line and the rendering of the old focus area.
