### ISSUE TITLE
[Feature] Organising content and notes, viz., Zettelkasten, Mind-mapping Support

### ISSUE THREAD

**Issue by sirinath** [taniarascia/takenote#458]
**Problem**
Provide better ways to organise notes and their interdependency and relationships among and within notes.

**Solution**
Facilitate visual thining and note organisation by supporting features like Zettelkasten, Mind-mapping, etc.

**Comment by kodyclemens** [comment]
The support for linking notes currently exists. What specific features from Zettelkasten are you referring to? The method seems to be quite unique and would require significant changes. Mind mapping seems like it would not be a fit for a note taking application but I'm not sure if I completely understand what you mean either.

**Comment by sirinath** [comment]
Simple maintain the relationship between the notes of facts on notes. This is like hyperlinks / anchor links in HTML but could be more advance. There should be a special view to view the relationships and edit the files or parts of them which are linked and the relationships themselves. Relationships can have labels, attributes and other metadata as well as content in the notes and files.

**Comment by taniarascia** [comment]
Hello, unfortunately that is far beyond the scope of what TakeNote is intended to do, so it might be better to search specifically for a note-taking app that already has those capabilities built in.
