### ISSUE TITLE
[Windows] Copy text shortcut creates a new Category

### ISSUE THREAD

**Issue by alphonseb** [taniarascia/takenote#46]
On Windows, `CTRL + C` doesn't copy the text and creates a new Category instead.

**Comment by taniarascia** [comment]
Maybe we can use alt/option shortcuts instead of control for Windows compatibility.

**Comment by alphonseb** [comment]
Yes, ctrl+shift+c would have been nice too but Chrome uses it to open the dev tools, I guess alt is the best solution. Maybe you can keep CTRL for Mac ? I feel it's still more convenient to hit that key instead of Option

**Comment by taniarascia** [comment]
I'll do `option` + `control` + `key` for now, unless someone has a better idea.
