### ISSUE TITLE
[Feature]plantuml or sequence diagram support

### ISSUE THREAD

**Issue by xu4wang** [taniarascia/takenote#481]
**Problem**
I need to draw diagrams in my notes, usually I use plantuml. How shall I keep my diagrams in takenote too? 

**Solution**
It will be great if we can support plantuml or sequence diagram syntax, with some javascript libray to render them in preview mode.

**Notes**

**Comment by taniarascia** [comment]
Hi there, thanks for the suggestion but unfortunately that is beyond the scope of what has ever been planned for TakeNote, so I'm going to close this issue.
