### ISSUE TITLE
[Bug] Scrollbar in Firefox

### ISSUE THREAD

**Issue by ndaidong** [taniarascia/takenote#496]
**To Reproduce**
Create a  quite long content note. 
Switch to preview mode and scroll to the bottom until you see the very last line.

**Expected behavior**
You should see the last line and, if possible, the last blank line.

![Takenote scrollbar - Chromium based browser](https://user-images.githubusercontent.com/1809619/110228494-32aa9880-7f34-11eb-81e3-d8cb82147cab.png)

**Actual behavior**
But, you will see only a half of the last line.

![Takenote scrollbar - Gecko based browser](https://user-images.githubusercontent.com/1809619/110228497-34745c00-7f34-11eb-8dab-dd7f938927eb.png)

**Notes**
This issue occurs on Firefox. There is no problem with the chromium based browsers. Maybe just  a little hack of CSS.

**Comment by arbaz52** [comment]
for the class ``` .previewer.previewer_direction-ltr ```
if we use ``` padding-bottom: 0px; bottom: 39px; ```
it fixes the issue. for chrome.

**Comment by arbaz52** [comment]
I will create a pull request to fix this.
