### ISSUE TITLE
Preview mode content overflowing from the top

### ISSUE THREAD

**Issue by arbaz52** [taniarascia/takenote#501]
**To Reproduce**
Open any note or scratchpad in preview mode.

**Expected behavior**
It should have a space/padding between the top of viewport and the content.

**Actual behavior**
Content in preview mode is overflowing from the top

**Notes**
![image](https://user-images.githubusercontent.com/16359931/114128812-a9152e80-9916-11eb-8660-c1c1cd2cd1ef.png)

**Comment by arbaz52** [comment]
this can be fixed by using `top: 0px` as we're not using vertical padding.
because of `bottom: 39px` the content has overflowed from the top.

**Comment by taniarascia** [comment]
Thanks. The one time I don't check out a PR because it's so small that I think nobody messed anything up, I was wrong. Lesson learned!

**Comment by arbaz52** [comment]
@taniarascia I made a PR for using `bottom: 39px` instead of `padding-bottom: 39px` [Pull Request](https://github.com/taniarascia/takenote/pull/498) #498 for the overflowing of content from the bottom inside the previewer, but I did check the previewer and it did not cause this.

**Comment by taniarascia** [comment]
Thanks for fixing it!
