### ISSUE TITLE
[Bug] Accessibility - Keyboard Navigation

### ISSUE THREAD

**Issue by cngodles** [taniarascia/takenote#503]
https://takenote.dev/app

**To Reproduce**
Attempt to navigate the app without a mouse.

**Expected behavior**
Should be able to access all features sans mouse.

**Actual behavior**
There are several instances where using the `tab` key results in the focus of an item without highlighting it. This hinders users further who can only access the app using a keyboard. You are also essentially trapped in the editor if you are using it with only a keyboard. There is an exception, however, where you can use certain keyboard shortcuts (such as `Ctrl + Atl + F`) as an escape.

**Notes**

More reading in issue #495. You also lose the ability to use the `tab` key for navigation when editing a note. Take the Github editor as an example, where using the `tab` key escapes you from the editor, instead of writing out a tab. Adding tabs is a pain in these types of text editors, where adding 4 spaces is used as a replacement when writing inline code, etc.

There appear to be many opportunities to improve this throughout, such as allowing a user to navigate available notes using arrow keys.

**Comment by Bartek532** [comment]
I partly closed this issue in #509, please look for it 😄
