### ISSUE TITLE
Give feedback when "Save" is pressed

### ISSUE THREAD

**Issue by alphonseb** [taniarascia/takenote#53]
Right now when pressing the "Save" button the user doesn't really know if the saving was indeed done. 
Some feedback would be nice, maybe a discrete message that fades after some time.

**Comment by taniarascia** [comment]
This will eventually be done automatically in the background, once hooked up to GitHub. It should - like Todoist - have a "syncing..." displayed while it's doing it. However, it saves too fast for that to be displayed right now.

**Comment by taniarascia** [comment]
A loader will display, but it's too fast right now.
