### ISSUE TITLE
Preview rendered html in notes

### ISSUE THREAD

**Issue by Hussain-7** [taniarascia/takenote#573]
## Todo's:
- Just like in github preview we should be able to write markdown in notes and view it.
- Using tags used in markdown.
- A button can be created that can preview the current note's rendered html.

**Comment by bilalafzal01** [comment]
For enhacement of marketup we can make use of `mermaid`, which allows us to write diagrams as code.

[Mermaid](https://mermaid-js.github.io/mermaid/#/)

An example of such diagrams is such as:

```mermaid
flowchart TD
    A[Start] --> B{Is it?}
    B -- Yes --> C[OK]
    C --> D[Rethink]
    D --> B
    B -- No ----> E[End]

```
