### ISSUE TITLE
Drag and drop not working 

### ISSUE THREAD

**Issue by jeffslofish** [taniarascia/takenote#60]
I see that drag and drop was added previously, but I cannot get it to work in Chrome, Firefox, or Safari on macOS.

I would expect to be able to drag a note to favorites, trash, or a category, but I can do none of these. I am able to drag a note around, but when I drop it on any of these items it moves back to its original place and doesn't move to the appropriate folder.

**Comment by taniarascia** [comment]
I see adding a category stopped working, the other ones work fine for me in Chrome, FF, and Safari on macOS.

**Comment by taniarascia** [comment]
Note that when you're in "All notes", you won't see the change.

**Comment by jeffslofish** [comment]
Ok, yes, it is just the categories that aren't working for me as well.....I was in "all notes" =)

**Comment by taniarascia** [comment]
Cool. I just fixed that. Thanks. :)
