### ISSUE TITLE
Error Message while running the npm i command

### ISSUE THREAD

**Issue by rishilin09** [taniarascia/takenote#608]
After cloning the project, I ran the **npm i** command and after some while I got this message. I again cloned the project and ran the same command again but I still got the same error.

**Can anyone tell me where am i going wrong here?**

npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\cwebp-bin',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\cwebp-bin'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\cwebp-bin'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\mozjpeg',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\mozjpeg'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\mozjpeg'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\optipng-bin',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\optipng-bin'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\optipng-bin'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\cypress',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\cypress'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\cypress'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\gifsicle',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\gifsicle'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\gifsicle'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\pngquant-bin',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\pngquant-bin'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\pngquant-bin'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Rishi\MCA\Summer Term Project\takenote\node_modules\cwebp-bin'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\cwebp-bin'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Rishi\MCA\Summer Term Project\takenote\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Rishi\MCA\Summer Term Project\takenote\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@18.12.1 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Rishi\MCA\Summer Term Project\takenote\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Rishi\MCA\Summer Term Project\takenote\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Rishi\MCA\Summer Term Project\takenote\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Rishi\MCA\Summer Term Project\takenote\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Rishi\MCA\Summer Term Project\takenote\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:207:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Users\Rishi\AppData\Local\Programs\Python\Python311\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Users\Rishi\AppData\Local\Programs\Python\Python311\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:412:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Rishi\\MCA\\Summer Term Project\\takenote\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Rishi\MCA\Summer Term Project\takenote\node_modules\node-sass
npm ERR! gyp ERR! node -v v18.12.1
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

**Comment by Munaf-Divan** [comment]
Hello @rishilin09, can you be more specific and provide the steps to reproduce the issue? I would also like to ask you to please provide your machine configuration and the node version you are using.

**Comment by rishilin09** [comment]
> Hello @rishilin09, can you be more specific and provide the steps to reproduce the issue? I would also like to ask you to please provide your machine configuration and the node version you are using.

**Comment by rishilin09** [comment]
Hello **@Munaf-Divan**, I wanted to take help from this project to make my version of takenote so I followed the installation steps as mentioned in the README file. At first I cloned the project and after cloning I changed the directory to takenote as given in the instruction. After changing the directory, the next step was to run the **npm i** command to install the npm libraries. So I did the same thing and waited for the process to be completed but after a while the above error message got  displayed and the process got terminated. Below is the log file of the command
[2023-04-23T10_21_46_979Z-eresolve-report.txt](https://github.com/taniarascia/takenote/files/12209304/2023-04-23T10_21_46_979Z-eresolve-report.txt)


node version => **v18.12.1**
npm version => **9.7.1**


**System Configuration**
Host Name:                 RISHI-PC
OS Name:                   Microsoft Windows 11 Home Single Language
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Rishi
Registered Organization:   N/A
Product ID:                00356-24514-74975-AAOEM
Original Install Date:     9/28/2022, 1:52:50 PM
System Boot Time:          7/30/2023, 12:28:46 PM
System Manufacturer:       LENOVO
System Model:              82K2
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~1908 Mhz
BIOS Version:              LENOVO H3CN30WW(V2.00), 6/28/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              00004009
Time Zone:                 (UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi
Total Physical Memory:     5,996 MB
Available Physical Memory: 281 MB
Virtual Memory: Max Size:  19,834 MB

**Comment by Munaf-Divan** [comment]
Hi @rishilin09, I don't know if it's the right solution but you can try out below command.

npm i --legacy-peer-deps

The issue seems to be, conflicting dependencies, so this above command will ignore such conflict. Try it and let me know if it works.

**Comment by rishilin09** [comment]
Hello **@Munaf-Divan** the command you provided didn't worked and it is throwing the same npm error again

**Comment by rishilin09** [comment]
Hello everyone I looked into the solution and I found out the solution for the above issue from stackoverflow

https://stackoverflow.com/questions/45801457/node-js-python-not-found-exception-due-to-node-sass-and-node-gyp#53009640

Try each solution and solve the problem

**Comment by jreflores** [comment]
Managed to fix this by replacing `node-sass` line in `packages.json` to `"sass": "^1.22.10"`
