### ISSUE TITLE
Rewrite shortcuts

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#63]
They should be ctrl+alt not alt+ctrl.

**Comment by dong-alex** [comment]
I assume you are looking for a change like this?
From
![Screen Shot 2019-10-15 at 11 18 25 PM](https://user-images.githubusercontent.com/23242741/66890208-8369cc00-efa2-11e9-9a79-52fbae84ca26.png)
To
![Screen Shot 2019-10-15 at 11 16 34 PM](https://user-images.githubusercontent.com/23242741/66890209-84026280-efa2-11e9-8ceb-caad5bb3874e.png)
