### ISSUE TITLE
[Notes] Add ability to add new note from trash. Do not hide new button on trash

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#65]
Right now, new button is hidden when trash folder is selected. Instead, just make a new note in “all notes”.

**Comment by MartinRosenberg** [comment]
I think the way it works now is a better UX. If the user is on the trash folder, and creates a new note, I see two ways it could work:

1. The view stays on the Trash folder, and the user might get confused as to where the new note is.
2. The view moves to All Notes, and the user might not realize they're no longer looking at Trash.

**Comment by taniarascia** [comment]
Replace with empty trash button instead?

**Comment by MartinRosenberg** [comment]
Putting that button in the same place as the add note button could be dangerous, if someone _does_ expect the add note button there, and accidentally empties the trash.

I'm also not a UI expert, so I'm not sure what to suggest as an alternative.

**Comment by taniarascia** [comment]
UI for options definitely needs some work. Maybe new note can be moved to be online with allnotes and trash, like on Evernote.

**Comment by justDOindev** [comment]
I can do this!

**Comment by justDOindev** [comment]
How about when you are in the trash folder and click "New Note" a menu comes up with the different folders you can add it to.

**Comment by justDOindev** [comment]
can I be assigned to this? I have it working the way @taniarascia mentioned.

**Comment by taniarascia** [comment]
No assignment needed, feel free to open a PR.

**Comment by taniarascia** [comment]
Closed in #93
