### ISSUE TITLE
[Notes] On initial load, create new note if notes array is empty

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#67]
A user landing on the page can be confused right now, believing they can type immediately. However, the app does not begin with any active note, nor does it have an example note. 

In the case that no notes exist on initial load, create a new empty note. Do not create a new empty note if they delete all notes - only initial load.

**Comment by taniarascia** [comment]
#9 creates an example note that can populate on first load.

**Comment by vincentdoerig** [comment]
I had drafted this function earlier today [here](https://github.com/vincentdoerig/takenote/blob/add-example-note/src/api/index.ts#L7-L28), but there probably is a nicer way of doing it.

**Comment by MartinRosenberg** [comment]
@vincentdoerig I like that your approach also handles #9. Will you be making a PR?
