### ISSUE TITLE
[Testing] Test cases

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#73]
Just leaving notes here on the functionality that should be tested.

### Notes

- [x] create a note
- [x] update a note
- [x] send a note to trash
- [x] add a note to favorites
- [x] add a note to category
- [x] permanently delete a note
- [x] restore a deleted note
- [x] empty trash
- [x] search notes
- [x] list proper notes per folder or category in order

### Categories

- [x] create a category
- [x] delete a category

### Settings/Sync 

- [x] sync a note

**Comment by rsuttles58** [comment]
From looking at the two PRs, it looks like this issue is closed out?  If not, I'm happy to write additional Cypress testing if needed.

**Comment by taniarascia** [comment]
@rsuttles58 I haven't wanted to request too much help here until the GitHub auth and sync is all set...I don't know what method we'll have to do to get around authenticating. Maybe a "test mode" that doesn't need to log in, and just tests the functionality of the app? But even that will be hard, since we'll have to mock all the GitHub gist responses....

**Comment by taniarascia** [comment]
We can definitely increase coverage with testing-library component tests. As for e2e cypress tests, will need to wait until Gist integration is complete and figure out how to mock all that out.

**Comment by leofrozenyogurt** [comment]
Hey all hoping to add some tests to the project as well as other features; it looks like the previous tests are failing when run with cypress open; cypress cannot continue to the note creation page due to being stuck before the login.

**Comment by taniarascia** [comment]
We definitely need to have some sort of logged out mode, as mentioned in #172. Tests are failing since authentication was added because it cannot get past the auth to the correct route.

**Comment by codytowstik** [comment]
+1 for logged out mode.. but once the authentication is implemented, i'd be happy to add some mocks, too.

**Comment by taniarascia** [comment]
I’m thinking we might not need a logged out mode, the component tests can just bypass or mock the authenticated state, especially now that I have complete control of it and it’s not relying on Auth0. I’m not sure about e2e though.

**Comment by codytowstik** [comment]
I'm thinking logged out/offline mode would be cool if we ever implement any sort of offline caching that uploads when you log in again (or reconnect to internet).

btw I am not sure there is a test for 'updating a note' which is checked

**Comment by codytowstik** [comment]
Is anyone working on the last 3 tests? If not ill assign this to me and close it out. I'll open a new ticket with more test ideas.

**Comment by taniarascia** [comment]
Sounds good!

**Comment by codytowstik** [comment]
Tests mentioned in this issue complete, see https://github.com/taniarascia/takenote/issues/228 for more ideas.
