### ISSUE TITLE
Provide an issue template for reference from the contributor

### ISSUE THREAD

**Issue by mirazmamun** [taniarascia/takenote#75]
**Scope**: contribution from the community.

**Description**: It would be much helpful for the contributors to have a common and guiding template for creating issue. I know this is kind of egg and chicken problem that this issue is being created to create a proper issue. Anyway, I know it is quite trivial to create a Template for issue from setting interface. Just need someone to do it.

**Associated Resources**: Although it is trivial to find the relevant document, here is a quick link for it to save searching for it, https://help.github.com/en/articles/creating-issue-templates-for-your-repository

**Comment by taniarascia** [comment]
Thanks for the idea! Added a bug and feature template.
