### ISSUE TITLE
preview markdown on the editor?

### ISSUE THREAD

**Issue by rsz52624** [taniarascia/takenote#77]
any plans for preview markdown on the editor?

**Comment by taniarascia** [comment]
It’s an idea, but I’m not 100% sure. There could be a preview toggle, but this is not a feature I want much and especially not if it slows down the app at all.

**Comment by Publicker** [comment]
I think that I can do something with this!

**Comment by taniarascia** [comment]
Closed in #119

**Comment by rsz52624** [comment]
@Publicker  #119 

The code block is not correctly left-aligned.

![Capture](https://user-images.githubusercontent.com/46218721/67276335-10f37180-f4f7-11e9-875c-84d812ce59ef.PNG)
