### ISSUE TITLE
[Feature] Pop up to confirm exit ?

### ISSUE THREAD

**Issue by omkarsgit** [taniarascia/takenote#78]

**Comment by kleyu** [comment]
This could be probably achieved by listening to `beforeunload` window event. It pops up a native browser api box just before exiting tab (unloading).

Here's a example implementation of it using React Hook: https://github.com/jacobbuck/react-beforeunload

**Comment by taniarascia** [comment]
We don't want to confirm exit on every exit, only on exit where data has not been synced.

**Comment by Jfelix61** [comment]
I see this has become stale, may I take this issue? @taniarascia

**Comment by taniarascia** [comment]
Sure, no need to ask!

**Comment by taniarascia** [comment]
Closed in #257.
