### ISSUE TITLE
Add GitHub authentication

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#8]
Add GitHub authentication.

- Ability to log in with GitHub
- Connect TakeNote with a single gist
- Display all individual notes as `.md` files within TakeNote Gist.

**Comment by hankolsen** [comment]
I believe this requires server side code, to be able to send a POST to github, in order to exchange a code for an access token:
Step 2 here: https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/

**Comment by taniarascia** [comment]
That’s true, you need a server side endpoint to access the token. I could either serve the entire app from Express and have an api endpoint, or make a microservice to handle the API call...

**Comment by hankolsen** [comment]
I love Netlify's lambda functions!

**Comment by taniarascia** [comment]
That might be an interesting way to go. Regarding API calls, it should need one for auth, and one for sync.

**Comment by hankolsen** [comment]
It's really convenient to serve both the front end and backend on Netlify.

**Comment by taniarascia** [comment]
Do you know any good resources for serverless authentication with Netlify? I wonder where I would store the access token if I don't serve the app from Express or something...the only option is saving in localStorage, which I don't want to do...

**Comment by hankolsen** [comment]
Hmm, what's wrong with localStorage?
The only options you have is cookie or localStorage, I believe...

**Comment by taniarascia** [comment]
localStorage has the possibility of XSS. But Auth0 takes care of this without having to store anything on the client, so I figured it out.

**Comment by taniarascia** [comment]
GitHub auth is added. GitHub Gist integration to be added.

**Comment by taniarascia** [comment]
Closed in #151
