### ISSUE TITLE
Create an example note

### ISSUE THREAD

**Issue by taniarascia** [taniarascia/takenote#9]
Each new TakeNote account should begin with an example note, that explains everything you can do.

- Creating notes
- Creating categories
- Keybindings (`ctrl + n` for new note, for example)
- Sync

**Comment by waellerbe** [comment]
I just happen to have some experience with Markdown, and I welcome the opportunity to contribute to this incredible project. Documentation is a strong ability in my current skill set. Thank you for your consideration.

**Comment by vincentdoerig** [comment]
Are you working on this @waellerbe? Otherwise I'd like to have a go at this.

**Comment by vincentdoerig** [comment]
I quickly put this together. Feedback appreciated

# Welcome to Takenote!

Takenote is a  web-based note-taking app with GitHub sync (soon™️) and Markdown support. Check out the project on [Github](https://github.com/taniarascia/takenote).

## Features

- Plain text notes with Markdown highlighting and frontmatter metadata
- Add, update, download, temporarily delete and delete notes
- Add, update, and delete categories
- Add notes to categories or mark note as favorite
- Keybinding shortcuts for common actions
- Settings for light/dark mode, sync frequency, and Vim mode
- Multi-cursor editing

## Creating and adding notes to a category

- Click on the `+` icon in the sidebar
- Enter a name for the category
- Move any existing notes by dragging and dropping the note into the category
	- or select the category in the dropdown by clicking on the three dots next to the notes name
- Select the category name
- Done!

## Favorite, delete or download a note

- Click on the three dots next to the name of the note
- Click 'Mark as Favorite' if you want to favorite your note
- Click 'Move to trash' if you want to delete a note
	- you can always recover a deleted note by clicking 'Trash' in the sidebar and then 'Restore from trash'
- Click 'Download' if you want to download your note as a markdown file to your device

## Dark mode and Vim mode

Dark mode and Vim mode can be enabled in the settings which can be accessed by clicking the settings icon in the sidebar.

## Sync

Currently, notes are stored in your browsers localStorage. 

In the future, you will be able to sync your notes by clicking on the 'Sync notes' button in the sidebar. Your notes will be stored on Github as a gist file.

## Keyboard shortcuts

| Action          | Windows/Linux Shortcut | Mac Shortcut           |
|-----------------|------------------------|------------------------|
| Create note     | `CTRL` + `ALT` + `N`   | `CTR` + `OPTION` + `N` |
| Delete note     | `CTRL` + `ALT` + `W`   | `CTR` + `OPTION` + `W` |
| Create category | `CTRL` + `ALT` + `C`   | `CTR` + `OPTION` + `C` |
| Download note   | `CTRL` + `ALT` + `D`   | `CTR` + `OPTION` + `D` |
| Sync note       | `CTRL` + `ALT` + `S`   | `CTR` + `OPTION` + `S` |

## Markdown support

# H1 Heading
## H2 Heading
### H3 Heading
#### H4 Heading
##### H5 Heading
###### H6 Heading

This is a link to the [takenote project page](https://github.com/taniarascia/takenote).

This is **bold text** and __this as well__. Italic text is created like *this*. You can even combine the two to create ***bold italic*** text.

```
const helloWorld = () => {
  console.log('Hello World!')
}
helloWorld()
```
The code above is a code block fenced with three back-ticks. Inline code can be created by wrapping it in `back-ticks`.

**Comment by taniarascia** [comment]
Note content is created (#87), resuming work in #67.

**Comment by waellerbe** [comment]
> Are you working on this @waellerbe? Otherwise I'd like to have a go at this.

@vincentdoerig Your example note is excellent. Looking forward to future development on this project.

@taniarascia  Thank you for approving the entry from Vincent. I will continue to follow the development of this project.
